src/Routes.tsx, src/components/Header/Header.tsx, src/views/Transactions/Transactions.styles.tsx, src/views/Transactions/Transactions.tsx, src/views/Transactions/index.ts, src/views/Transactions/useTransactionsView.ts, src/views/index.ts
=> feat: basic unconnected view for Transaction page

package.json, src/views/Transactions/Transactions.tsx, src/views/Transactions/createTransactionModel.ts, src/views/Transactions/createTransactionTableJSX.tsx, src/views/Transactions/formatTransactionData.tsx, src/views/Transactions/useTransactionsView.ts, yarn.lock
1) Create the Transaction model that will be formatted from the raw event data.
2) Use that Model to create the rows and cells for Table.
https://app.shortcut.com/uma-project/story/4863/create-interface-and-convert-function-for-transactions
=> feat: Create TransactionModel and convert data to Rows & cells

package.json, src/components/PoolForm/AddLiquidityForm.tsx, src/components/PoolForm/PoolForm.tsx, src/components/PoolForm/RemoveLiquidityForm.tsx, src/components/PoolSelection/PoolSelection.tsx, src/components/SendAction/useSendAction.ts, src/data/tokens.json, src/state/connection.ts, src/state/poolsApi.ts, src/utils/bridge.ts, src/utils/chains.ts, src/utils/constants.ts, src/utils/pool.ts, src/views/Pool.tsx, yarn.lock
Integrates sdk pool client. Minor changes were needed to pool logic. 
Before this is merged, it will automatically run on kovan, which is how I tested it. so you should be good to actually run through the pool tab UI.
=> feat: integrate v2 pool client into pool tab

src/components/SendAction/SendAction.tsx
Fixes https://app.shortcut.com/uma-project/story/5284/update-fee-section-to-not-always-say-ethereum-mainnet-gas-fee
=> fix(across-v2): change ethreum gas fees to dest chain fees

src/assets/across-emptystate-clouds.svg, src/views/Transactions/Transactions.styles.tsx, src/views/Transactions/Transactions.tsx, src/views/Transactions/TransactionsTable/MobileTransactionsTable.tsx, src/views/Transactions/TransactionsTable/MobileTransactionsTableWithPagination.tsx, src/views/Transactions/TransactionsTable/TransactionsTable.styles.tsx, src/views/Transactions/TransactionsTable/TransactionsTable.tsx, src/views/Transactions/TransactionsTable/TransactionsTableWithPagination.tsx, src/views/Transactions/useTransactionsView.ts
Empty and loading states for tx history:
=> feat: empty and loading states for tx history

src/components/AddressSelection/AddressSelection.styles.ts, src/components/ChainSelection/ChainSelection.styles.tsx, src/data/token-order.json, src/data/tokens.json, src/utils/constants.ts
Makes the order in which the tokens appear in the dropdown configurable
=> feat(across-v2): make order of tokens configurable

src/views/Transactions/TransactionsTable/createMobileTransactionTableJSX.tsx, src/views/Transactions/TransactionsTable/createTransactionTableJSX.tsx
Story details: https://app.shortcut.com/uma-project/story/5337
=> fix: point to correct block url.

package.json, src/components/CoinSelection/useCoinSelection.tsx, src/components/SendAction/useSendAction.ts, src/data/tokens.json, src/hooks/useBalance.ts, src/hooks/useBridge.ts, src/hooks/useBridgeFees.ts, src/utils/bridge.ts, src/utils/constants.ts, yarn.lock
=> feat: add relay and lp fee logic

src/components/PoolForm/PoolForm.tsx, src/views/Pool.tsx
=> fix: set eth address back to zero, update user/pool indexing

src/components/PoolSelection/PoolSelection.tsx, src/views/Pool.tsx
fixes balances showin in the pool currency dropdown
=> fix: pool drop down balances

src/components/PoolForm/AddLiquidityForm.tsx, src/components/PoolForm/PoolForm.tsx, src/components/PoolForm/RemoveLiquidityForm.tsx, src/views/Pool.tsx
Pool tab action button was switching to wrong network.
Replaces hard coded chain id with the chain id based on pool client
=> fix: fix pool button network switcher

src/utils/constants.ts
Signed-off-by: Tulun <jaykiraly@gmail.com>
=> remove mainnet per spec from alex

src/components/PoolForm/AddLiquidityForm.tsx, src/components/PoolForm/PoolForm.tsx, src/components/PoolForm/RemoveLiquidityForm.tsx, src/data/routes_1_0x6Bb9910c5529Cb3b32c4f0e13E8bC38F903b2534.json, src/data/routes_42_0xD449Af45a032Df413b497A709EeD3E8C112EbcE3.json, src/state/poolsApi.ts, src/utils/config.ts, src/utils/constants.ts, src/utils/pool.ts, src/views/Pool.tsx
This removes need for weth address env as it can be discovered from on chain hubpool contract
=> improve: update kovan routes, add weth address to routes

src/views/Transactions/Transactions.styles.tsx, src/views/Transactions/Transactions.tsx, src/views/Transactions/TransactionsTable/createMobileTransactionTableJSX.tsx, src/views/Transactions/TransactionsTable/createTransactionTableJSX.tsx
Story details: https://app.shortcut.com/uma-project/story/5336
=> feat: When sending ETH, the transaction history page says I sent WETH

.husky/pre-commit, package.json, src/components/SendAction/SendAction.tsx, src/components/SendAction/useSendAction.ts, src/hooks/useBlock.ts, src/hooks/useBridgeFees.ts, src/utils/constants.ts, src/views/About.tsx, yarn.lock
This primarily makes polling configurable and slower (from 5 seconds to 30 seconds by default). This also adds husky linting
=> feat: make block poller configurable

src/components/Header/Header.styles.tsx
=> improve: apply issue 190 some minor css changes

src/components/Dialog/Dialog.styles.tsx
Story details: https://app.shortcut.com/uma-project/story/5448
=> fix send to modal height

.husky/pre-commit, package.json, src/components/SendAction/useSendAction.ts, src/data/routes_1_0x6Bb9910c5529Cb3b32c4f0e13E8bC38F903b2534.json, src/data/routes_42_0x8d84F51710dfa9D409027B167371bBd79e0539e5.json, src/data/routes_5_0xA44A832B994f796452e4FaF191a041F791AD8A0A.json, src/hooks/useBridgeFees.ts, src/hooks/useSendForm.tsx, src/utils/config.ts, src/utils/constants.ts, yarn.lock
This adds goerli, and updates the kovan deployment.  Also fixes linting staged files.
=> improve: add and update routes for testnets

package.json, src/state/poolsApi.ts, src/utils/bridge.ts, src/utils/constants.ts, yarn.lock
Updates config store addresses and uses the new client in the across sdk. Waiting on publishing sdk before we can merge.
=> chore: migrate to config store contract

src/components/AddressSelection/useAddressSelection.ts, src/components/ChainSelection/useChainSelection.ts
=> fix: ensure dropdowns get initized with form state

src/components/AddressSelection/AddressSelection.styles.ts, src/components/AddressSelection/AddressSelection.tsx, src/components/CoinSelection/CoinSelection.styles.ts, src/components/CoinSelection/CoinSelection.tsx, src/components/CoinSelection/useCoinSelection.tsx, src/components/SendAction/useSendAction.ts, src/hooks/useBridgeFees.ts
Story details: https://app.shortcut.com/uma-project/story/5497
=> show a disabled dropdown

README.md, src/utils/constants.ts, src/views/Pool.tsx
Story details: https://app.shortcut.com/uma-project/story/5110
=> feat: Banner notification

src/views/Transactions/TransactionsTable/createMobileTransactionTableJSX.tsx, src/views/Transactions/TransactionsTable/createTransactionTableJSX.tsx
This filters out and creates a warning when we see a transaction with an unsupported tokens. Tokens can be unsupported if they were added to the contracts,  and a transfer was done outside of the UI but we have not regenerated the routes to support it yet.  Previously this would crash the UI.
=> fix: prevent tx page crashing with unknown token transfer

README.md, src/state/transferHistory.ts, src/utils/constants.ts
Remove unneeded constants for spoke and hub chains, move lowest block into the chain info
=> improve: clean up unused configs

src/components/Pagination/Pagination.styles.tsx, src/components/Pagination/Pagination.tsx, src/utils/localStorage.ts, src/views/Transactions/Transactions.tsx, src/views/Transactions/TransactionsTable/MobileTransactionsTableWithPagination.tsx, src/views/Transactions/TransactionsTable/TransactionsTable.styles.tsx, src/views/Transactions/TransactionsTable/TransactionsTableWithPagination.tsx, src/views/Transactions/useTransactionsView.ts
=> feat(tx-history): add adjustable tx history page size 

package.json, src/hooks/useSendForm.tsx, yarn.lock
The issue is sometimes send button does not enable when it should. This is due to only selecting from chain, internally not narrowing down to a single route.
=> fix: make sure to create selected route when choosing from chain

src/components/Layout/Layout.tsx, src/views/Confirmation/Confirmation.styles.ts, src/views/Confirmation/Confirmation.tsx
Story details: https://app.shortcut.com/uma-project/story/5541
=> feat: [sc-5541] link to transfer page on deposit confirmation screen

src/Routes.tsx, src/components/Header/Header.tsx, src/utils/constants.ts
Story details: https://app.shortcut.com/uma-project/story/5585
=> fix: [sc-5585] REACT_APP_MIGRATION_POOL_V2_WARNING needs to be independent of migration configuration

src/state/chainApi.ts, src/state/hooks.ts, src/views/Pool.tsx
Signed-off-by: amateima <amatei@umaproject.org>
=> fix: fix balances in Pool tab

src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json
=> chore: remove dai from optimism routes

src/components/GlobalStyles/GlobalStyles.tsx, src/components/Pagination/Pagination.styles.tsx, src/components/Table/Table.styles.tsx, src/views/Transactions/Transactions.styles.tsx, src/views/Transactions/Transactions.tsx, src/views/Transactions/TransactionsTable/MobileTransactionsTableWithPagination.tsx, src/views/Transactions/TransactionsTable/TransactionsTable.styles.tsx, src/views/Transactions/TransactionsTable/createMobileTransactionTableJSX.tsx
This PR brings a couple of UI improvements:
- implement mobile layout according to Figma design
- add custom table horizontal scrollbars
- add Filled column on mobile
- adjust colours & spacing where necessary
**Result**
=> fix: improve table layout

src/components/Sidebar/Sidebar.tsx, src/components/Sidebar/useSidebar.ts, src/components/Wallet/Wallet.tsx, src/state/connection.ts, src/state/hooks.ts, src/utils/onboard.ts
display ens name if eligible for `Wallet` and `SideBar` components.
=> feat: display ens name if eligible

src/components/InformationDialog/InformationDialog.tsx
Story details: https://app.shortcut.com/uma-project/story/5591
=> fix: [sc-5591] update fee info modal

package.json, yarn.lock
=> chore: bump sdk version to fix tokenBalances issue

src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json
This reverts commit f3dccb0dfecb40e1610885cf90656747e5aed05c.
=> chore: add back dai to optimism routes

src/utils/config.ts
=> fix: fix call to isSuppotedChain on config

src/components/CoinSelection/useCoinSelection.tsx, src/hooks/useSendForm.tsx
Story details: https://app.shortcut.com/uma-project/story/5611
=> feat: add amount and asset to urlParams for send query.

src/components/AddressSelection/AddressSelection.tsx
Story details: https://app.shortcut.com/uma-project/story/5705
=> fix: Toggle is only on button not the wrapper.

src/utils/constants.ts
=> feat: add max relay fee percent env, default to 50

src/components/SendAction/SendAction.styles.ts, src/components/SendAction/SendAction.tsx, src/components/SendAction/useSendAction.ts
Story details: https://app.shortcut.com/uma-project/story/5702
=> feat: show pending TX link below send button

src/Routes.tsx, src/components/Header/Header.tsx, src/views/Rewards/Rewards.styles.tsx, src/views/Rewards/Rewards.tsx, src/views/Rewards/index.ts, src/views/Rewards/useRewardsView.ts, src/views/index.ts
Rewards page scaffolding for ongoing development.
Merge only into epic/rewards-page as we don't want incomplete work in master.
=> feat: Scaffolding for Rewards page.

src/views/Transactions/Transactions.tsx, src/views/Transactions/TransactionsTable/FillTxInfoModal.tsx, src/views/Transactions/TransactionsTable/createMobileTransactionTableJSX.tsx, src/views/Transactions/TransactionsTable/createTransactionTableJSX.tsx, src/views/Transactions/useTransactionsView.ts
Story details: https://app.shortcut.com/uma-project/story/5750
Copy to be provided by Korpi / Tim.
=> feat: Show Info popup on tx

src/components/Wallet/Wallet.tsx, src/views/Rewards/Rewards.styles.tsx, src/views/Rewards/Rewards.tsx, src/views/Rewards/comp/RewardBreakdown/RewardBreakdown.styles.tsx, src/views/Rewards/comp/RewardBreakdown/RewardBreakdown.tsx, src/views/Rewards/comp/RewardBreakdown/index.ts, src/views/Rewards/comp/index.ts
**Overview**
UI for Rewards Breakdown section of Rewards page.
Matches Design spec.
Note: The iconography is not finished yet, and links / modals are not provided, so this will be done in a future PR.
Testers, use the following templates to pass the pull request or to report issues that require a resolution.
Following these guidelines will help the developer respond more quickly to issues, but you are free to comment
in any way as needed to help resolve issues.
**Reporting QA Issues**
Testers should use Github comments to report issues with the PR. Use screenshots if relevant, you can also
check the [developer console](https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console)
to see if there are any logs which might be related. Use …
=> feat: rewards breakdown section.

src/views/Rewards/Rewards.tsx, src/views/Rewards/comp/RewardBreakdown/RewardBreakdown.styles.tsx, src/views/Rewards/comp/RewardBreakdown/RewardBreakdown.tsx, src/views/Rewards/comp/RewardHero/RewardHero.styles.tsx, src/views/Rewards/comp/RewardHero/RewardHero.tsx, src/views/Rewards/comp/RewardHero/index.ts, src/views/Rewards/comp/index.ts
Story details: https://app.shortcut.com/uma-project/story/5768
Note: Link and fancy BG not finished.
=> feat: Rewards hero (no fancy bg)

src/views/Transactions/Transactions.tsx, src/views/Transactions/TransactionsTable/createMobileTransactionTableJSX.tsx, src/views/Transactions/TransactionsTable/createTransactionTableJSX.tsx
Story details: https://app.shortcut.com/uma-project/story/5794
=> feat: [sc-5794] Only show info modal icon when there's a fill > 0 and less < 100

src/views/Rewards/comp/ConnectTableOverlay/ConnectTableOverlay.styles.tsx, src/views/Rewards/comp/RewardTableWithOverlay/RewardTableWithOverlay.styles.tsx, src/views/Rewards/comp/RewardTableWithOverlay/RewardTableWithOverlay.tsx
Story details: https://app.shortcut.com/uma-project/story/5817
=> feat: Fixed overlay for table.

src/views/Rewards/Rewards.tsx, src/views/Rewards/comp/RewardReferral/RewardReferral.tsx, src/views/Rewards/comp/RewardTable/RewardTables.styles.tsx, src/views/Rewards/comp/RewardTable/createMyReferralsTableJSX.tsx, src/views/Rewards/comp/RewardTableWithOverlay/RewardTableWithOverlay.tsx, src/views/Rewards/useRewardsView.ts
This PR showcase how to communicate with the referrals API.
=> feat: integrate the referrals testing api

src/components/Dialog/Dialog.styles.tsx, src/components/PoolForm/RemoveLiquidityForm.tsx, src/components/PoolForm/useSetLiquidityFormErrors.ts
Remove comma from checking for invalid number.
Story details: https://app.shortcut.com/uma-project/story/5834
=> fix: remove comma from check

src/assets/icons/arrow-16.svg, src/components/Table/Table.styles.tsx, src/components/Table/Table.tsx, src/views/Rewards/comp/ConnectTableOverlay/ConnectTableOverlay.styles.tsx, src/views/Rewards/comp/ConnectTableOverlay/ConnectTableOverlay.tsx, src/views/Rewards/comp/RewardReferral/RewardReferral.styles.tsx, src/views/Rewards/comp/RewardTable/RewardTable.tsx, src/views/Rewards/comp/RewardTable/RewardTables.styles.tsx, src/views/Rewards/comp/RewardTable/createMyReferralsTableJSX.tsx, src/views/Rewards/comp/RewardTablePagination/RewardTablePagination.styles.tsx, src/views/Rewards/comp/RewardTablePagination/RewardTablePagination.tsx
This PR improves the UI of the Referral table, so its much closer to the proposed design
=> fix: improve UI

api/limits.js, src/utils/bridge.ts, src/utils/constants.ts
Makes the cushion added in the prev PR adjustable via environment variables.
=> feat: allow cushion to be adjustable via envs

src/views/Rewards/comp/RewardMediumBlock/RewardMediumBlock.tsx
https://linear.app/uma/issue/ACX-100/change-rewards-multiplier-to-2
=> improve: change rewards multiplier to 2

public/index.html
https://linear.app/uma/issue/ACX-101/update-across-head-metadata
=> feat: update title and description metadata

api/_utils.js, api/pools.js
DefiLlama needs additional information like TVL in USD we should export full object from client
=> improve: pools route should return full pool client object

src/components/Header/Header.styles.tsx, src/components/SuperHeader/SuperHeader.tsx
=> fix: SuperHeader now shows with new sticky nabar

src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json, src/utils/constants.ts
=> feat: remove BADGER from pool and send.

api/_utils.js, api/limits.js, api/pools.js, api/suggested-fees.js
This is a temporary solution to test Vercel integration with Datadog. We can switch to a longer term solution like winston logger once this is confirmed to work.
=> improve(api): Add info and error logs

api/limits.js, api/suggested-fees.js
Very frequent errors due to clients calling with same origin and destination chain. We should return 400 instead of 500 here to indicate this is invalid input (same origin/destination or unsupported routes)
Happens a lot. About 153 times in the past hour. Looks like someone is checking a transfer from Arbitrum to Arbitrum. We should return 400 for this, not 500
START RequestId: 6afea5e4-7aa5-40af-9096-02bbf51e2c65 Version: $LATEST
2022-08-10T12:32:53.902Z	6afea5e4-7aa5-40af-9096-02bbf51e2c65	INFO	INFO(limits): Handling request to /limits [object Object]
2022-08-10T12:32:53.902Z	6afea5e4-7aa5-40af-9096-02bbf51e2c65	INFO	INFO(limits): Using provider at https://mainnet.infura.io/v3/b14cb6f39de44042802cf5c83d69c6f1
2022-08-10T12:32:53.902Z	6afea5e4-7aa5-40af-9096-02bbf51e2c65	INFO …
=> fix(api): Return 400 for invalid routes instead of 500

api/_utils.js, package.json, yarn.lock
Gas markup feature was added in https://github.com/across-protocol/sdk-v2/pull/75
=> improve(api): Add a gas buffer for relayer gas fee

.eslintrc.js, .github/workflows/lint-test.yaml, package.json, yarn.lock
Eslint is already included in CRA, but we didn't really enforce it.
=> ci: add eslint to github actions

src/Routes.tsx, src/components/Header/Header.tsx, src/views/Claim/Claim.styles.tsx, src/views/Claim/Claim.tsx, src/views/Claim/index.ts, src/views/index.ts
1. Create basic view for the Claim page
2. Connect to router.
3. Fix the header to properly highlight the route in the header.
=> feat: basic route + scaffolding of claim page

src/Routes.tsx, src/utils/config.ts, src/utils/constants.ts, src/views/Claim/hooks/useMerkleDistributor.tsx, src/views/NotFound/NotFound.styles.tsx, src/views/Pool.tsx
1. Renders staking view for matching pool url.
2. Renders 404 if that value is not contained in string[]
=> feat: render 404 or Staking view based on poolUrls array.

src/views/Pool.tsx
1. Reference account for pool to properly display position on Pool view.
=> fix: reference account for pool.

src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json
=> hotfix: remove tether

src/Routes.tsx, src/components/SuperHeader/SuperHeader.tsx
=> temp: add Tether banner

src/Routes.tsx, src/components/Banner/Banner.styles.tsx, src/components/Sidebar/Sidebar.tsx, src/components/SuperHeader/SuperHeader.tsx, src/state/hooks.ts
1. Check if address returned from Onboard is not an EOA. If so, warn users.
=> feat: show warning if address is a non-EOA

src/Routes.tsx
=> feat: remove banner

api/_utils.ts, api/limits.ts, api/suggested-fees.ts
These logs print every time API is requested, please comment if there are any logs worth keeping
=> improve: Remove debug level logs from API

api/_utils.ts, api/available-routes.ts
Reverts across-protocol/frontend-v2#270
=> Revert "fix: Disable all routes in API"

package.json, yarn.lock
**Overview**
This introduces price request bundling and light caching to the Coingecko
class, which should help to save on repetitive price lookups from the
backend/API coingecko endpoint.
Price lookups initiated from the front end _might_ be completed slightly
faster than previously, owing to the removal of the synchronous price
lookup to CoinGecko.
Users should not notice any functional differences. All price lookups should
continue to work, and price-related lookup errors should not be seen in the
console logs.
=> chore(package): Bump Across SDK-v2 => v0.1.25

src/hooks/index.ts, src/hooks/useCenteredInViewport.ts, src/hooks/useIsInCenterOfViewport.ts, src/stories/plaap/VerticalCardsList.stories.tsx, src/views/PreLaunchAirdrop/components/AirdropCard.tsx, src/views/PreLaunchAirdrop/components/VerticalCardsList.tsx
Can be tested via the `PLAAP/VerticalCardsList` story.
=> feat: vertical cards list for airdrop details page

src/hooks/index.ts, src/views/PreLaunchAirdrop/PreLaunchAirdrop.styles.tsx, src/views/PreLaunchAirdrop/PreLaunchAirdrop.tsx, src/views/PreLaunchAirdrop/components/AirdropCard.tsx, src/views/PreLaunchAirdrop/components/EligibilityFlow/EligibilityFlow.tsx, src/views/PreLaunchAirdrop/components/EligibilityFlow/index.ts, src/views/PreLaunchAirdrop/components/MoreInfoFlow/MoreInfoFlow.tsx, src/views/PreLaunchAirdrop/components/MoreInfoFlow/index.ts, src/views/PreLaunchAirdrop/components/SplashFlow/SplashFlow.tsx, src/views/PreLaunchAirdrop/components/SplashFlow/TitleSection.tsx, src/views/PreLaunchAirdrop/components/VerticalCardsList.tsx, src/views/PreLaunchAirdrop/usePreLaunchAirdrop.ts
Airdrop details flow. Visit `/airdrop` and click on `Airdrop details`.
=> feat: airdrop info flow

src/stories/plaap/SplashFlow.stories.tsx, src/stories/plaap/TravellerFlow.stories.tsx, src/utils/localStorage.ts, src/views/PreLaunchAirdrop/PreLaunchAirdrop.tsx, src/views/PreLaunchAirdrop/components/SplashFlow/SplashFlow.tsx, src/views/PreLaunchAirdrop/components/TravellerFlow/TravellerFlow.tsx, src/views/PreLaunchAirdrop/components/TravellerFlow/useTravellerFlow.ts
1. Welcome traveller flow accessible from "Learn about Across" button.
2. Going through the flow sets localStorage variable based on connected account.
Other PR will cover connecting this to backend data flows as needed.
=> feat:  connect traveller flow to account and local storage.

src/utils/serverless-api/prod/index.ts, src/utils/serverless-api/prod/rewards.ts, src/utils/serverless-api/types.ts, src/views/PreLaunchAirdrop/api/getPrelaunchRewards.ts, src/views/PreLaunchAirdrop/api/useGetPrelaunchRewards.ts, src/views/PreLaunchAirdrop/components/cards/LiquidityProviderCard.tsx, src/views/PreLaunchAirdrop/hooks/usePreLaunchAirdrop.ts
1. Integration with dev API.
2. Need to connect Discord user *and* link a wallet in order to test.
=> feat:  Jason/acx 304 rewards api integration with api

src/utils/constants.ts, src/views/PreLaunchAirdrop/components/cards/RewardsCard.tsx
The cards were a bit broken on mobile when an eligible wallet was connected on the airdrop page.
Before:
After:
=> fix: mobile eligible wallet airdrop cards

src/views/PreLaunchAirdrop/components/cards/BridgeTravelerCard.tsx
=> feat: Update Bridge copy.

src/views/PreLaunchAirdrop/components/cards/CommunityRewardCard.tsx
1. Clean up logic so we render the correct Icon.
=> fix: Clean up Icon logic

src/views/PreLaunchAirdrop/components/cards/CommunityRewardCard.tsx
Reference linked wallet instead of account.
=> fix: reference linked wallet

src/views/PreLaunchAirdrop/TempTestingButton.tsx
-Add second button that adds some rewards for testing.
=> feat: add 2nd button for QA

src/views/PreLaunchAirdrop/components/cards/BridgeTravelerCard.tsx, src/views/PreLaunchAirdrop/components/cards/BridgeUserCard.tsx, src/views/PreLaunchAirdrop/components/cards/CommunityRewardCard.tsx, src/views/PreLaunchAirdrop/components/cards/LiquidityProviderCard.tsx
1. Removed word 'now' from card copy.
=> fix: Copy update

src/views/PreLaunchAirdrop/components/LinkWalletModal.tsx
1. Add warning for non-EOA on Linked Wallet modal
2. Hide button with for non-EOA.
=> feat: Add warning on Linked Wallet Modal

src/components/LayoutV2/LayoutV2.tsx, src/views/Claim/Claim.styles.tsx, src/views/Claim/components/Card.tsx, src/views/Claim/components/ClaimAirdrop.tsx, src/views/Claim/components/DisconnectedWallet.tsx, src/views/Claim/components/StepCard.tsx, src/views/Staking/Staking.styles.tsx, src/views/Staking/components/StakingExitAction/StakingExitAction.styles.tsx, src/views/Staking/components/StakingForm/StakingForm.styles.tsx, src/views/Staking/components/StakingInputBlock/StakingInputBlock.styles.tsx, src/views/Staking/components/StakingReward/StakingReward.styles.tsx
Update all queries to new syntax.
=> fix: update to new QUERIES syntax

.storybook/main.js, package.json, src/stories/airdrop/VerticalCardsList.stories.tsx, src/utils/onboard.ts, yarn.lock
This fixes the local storybook build. I don't really know what exactly broke the build but with these changes, it works for me.
=> build: fix local storybook

package.json
This PR updates the SDK version number.
=> bump: SDK version

src/components/Footer/Footer.tsx, src/components/Layout/Layout.tsx, src/components/Sidebar/useSidebar.ts, src/views/About.tsx
Signed-off-by: Tulun <jaykiraly@gmail.com>
**Overview**
Testers, use the following templates to pass the pull request or to report issues that require a resolution.
Following these guidelines will help the developer respond more quickly to issues, but you are free to comment
in any way as needed to help resolve issues.
**Reporting QA Issues**
Testers should use Github comments to report issues with the PR. Use screenshots if relevant, you can also
check the [developer console](https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console)
to see if there are any logs which might be related. Use the following template when reporting a problem or issue with the PR.
You submit multiple comments using this template if there are multiple …
=> fixed links

src/assets/icons/help-24.svg, src/components/Text/Text.tsx, src/views/Airdrop/Airdrop.styles.tsx, src/views/Airdrop/components/ClaimAirdrop.tsx, src/views/Airdrop/components/EarnOptionCard.tsx, src/views/Airdrop/components/EligibleWalletFlow.tsx, src/views/Airdrop/components/StepCard.tsx, src/views/Airdrop/components/WaysToEarn.tsx
Airdrop claim flow UI updates. I still need to integrate some APYs but will do so in a separate PR.
=> feat: claim-flow UI updates

src/components/Footer/Footer.tsx, src/components/Layout/Layout.tsx
Fixes logos on old layout component. I didn't want use the new `<LayoutV2 />` because it broke the page and required some more refactors.
=> fix: old layout logos

src/components/PoolForm/AddLiquidityForm.tsx, src/components/PoolForm/PoolForm.tsx, src/components/PoolForm/RemoveLiquidityForm.tsx, src/views/Pool.tsx
Refetch pool info on success tx add/remove liquidity
=> feat: refetch pool on tx success

README.md, src/components/Footer/Footer.tsx, src/components/InformationDialog/InformationDialog.tsx, src/components/Layout/Layout.tsx, src/components/Sidebar/useSidebar.ts, src/views/About.tsx, src/views/Rewards/comp/RewardReferral/RewardReferral.tsx
This PR fix a issue with documentation links.
=> Fix: update doc links

src/views/Transactions/components/TransactionsTable/cells/StatusCell.tsx, src/views/Transactions/components/TransactionsTable/rows/DataRow.tsx, src/views/Transactions/components/TransactionsTable/rows/MobileDataRow.tsx, src/views/Transactions/utils.ts
Display "unprofitable" status for pending deposits on /transactions page.
=> feat: display "unprofitable" for pending transactions

src/ampli/index.ts
- add required enums for wallet events
Not sure about some change that were applied automatically 🤔
=> chore: bump ampli track v6

src/components/ChainSelection/useChainSelection.ts, src/components/PoolForm/AddLiquidityForm.tsx, src/components/PoolForm/RemoveLiquidityForm.tsx, src/components/RouteTrace/useRouteTrace.ts, src/components/Sidebar/Sidebar.tsx, src/components/Wallet/Wallet.tsx, src/hooks/useOnboard.tsx, src/utils/amplitude.ts, src/utils/index.ts, src/views/Airdrop/hooks/useAirdrop.ts, src/views/Referrals/comp/ConnectTableOverlay/ConnectTableOverlay.tsx, src/views/Referrals/comp/RewardReferral/RewardReferral.tsx, src/views/Rewards/hooks/useRewards.ts, src/views/Staking/Staking.tsx, src/views/Staking/components/ConnectWalletButton.tsx, src/views/Staking/hooks/useStakingView.ts, src/views/Staking/types.ts, src/views/Transactions/hooks/useMyTransactionsView.tsx
=> feat: connect wallet button clicked event analytics

src/ampli/index.ts, src/hooks/useOnboard.tsx, src/utils/amplitude.ts
=> feat: track user wallet props and disconnect

src/App.tsx, src/utils/constants.ts
Some small adjustments to the amplitude config.
=> refactor: refine ampli config

netlify.toml
Adding new http headers configs
=> feat: config http headers

src/hooks/useOnboard.tsx, src/utils/amplitude.ts
Sets the user_id to the wallet address.
=> feat: set user_id to wallet address

vercel.json
Adding new http header to monitoring content source
=> feat: add csp monitor

vercel.json
=> fix: missing csp headers

vercel.json
=> fix: add missing headers

vercel.json
=> fix: missing header source

vercel.json
=> fix: headers typo

src/utils/amplitude.ts
Use correct values for bridge fee tracking
=> fix: bridge fee tracking amplitude

src/Routes.tsx, src/components/Selector/Selector.tsx, src/components/TabsV2/index.tsx, src/utils/format.ts, src/utils/pool.ts, src/views/LiquidityPool/LiquidityPool.styles.tsx, src/views/LiquidityPool/LiquidityPool.tsx, src/views/LiquidityPool/components/Breadcrumb.tsx, src/views/LiquidityPool/components/PoolSelector.tsx, src/views/LiquidityPool/components/StatBox.tsx, src/views/LiquidityPool/components/UserStatRow.tsx, src/views/LiquidityPool/hooks/useAllLiquidityPools.ts, src/views/LiquidityPool/hooks/useUserLiquidityPool.ts, src/views/LiquidityPool/index.ts, src/views/Staking/components/StakingForm/StakingForm.styles.tsx, src/views/Staking/components/StakingForm/StakingForm.tsx
Closes ACX-541
Adds the read-only portion of the new pool page. Some loading states need to be refined though. Also this aims to get rid of redux toolkit for pool-related state management stuff.
=> feat: new pool page with read-data hooks

vercel.json
=> fix: Update csp headers

src/ampli/index.ts, src/components/Sidebar/Sidebar.tsx, src/hooks/useOnboard.tsx, src/index.tsx, src/utils/amplitude.ts, src/utils/localStorage.ts
Fixes ACX-568, ACX-570, ACX-571 and ACX-574
=> fix: wallet related amplitude bugs

package.json, yarn.lock
Fixes bug where rate model has Ubar = 0
=> fix: Update sdk-v2 to handle divide-by-0 bug in lpFeeCalculator

src/ampli/index.ts, src/components/SendAction/useSendAction.ts, src/utils/amplitude.ts
=> fix(amplitude): update ampli and replace `TransferTransactionConfirmed` with `DepositTransactionConfirmed` event

src/ampli/index.ts, src/components/SendAction/useSendAction.ts, src/utils/amplitude.ts
Rename `TransferDepositCompleted` event and props.
=> refactor: rename deposit ampli event and update sdk

src/components/WrongNetworkHeader/WrongNetworkHeader.tsx, src/components/WrongNetworkHeader/index.ts, src/components/index.ts, src/views/Bridge/Bridge.tsx, src/views/LiquidityPool/LiquidityPool.tsx, src/views/Staking/Staking.tsx
Displays super banner if incorrect network also on pool page.
=> fix: display wrong network banner on pool page

package.json, src/App.tsx, src/utils/tests/format.test.ts, yarn.lock
Try to integrate marketing-analytics browser. Please test before merging
=> feat: integrate @amplitude/marketing-analytics-browser

package.json, yarn.lock
As part of ACX-190, I added the bundle analyzer.
=> chore: add analyze script

src/hooks/useOnboard.tsx
Fixes Sentry issue ACROSS-FRONTEND-E
=> fix: `ValidationError` for some wallet connections

src/Routes.tsx, src/utils/lazy-with-retry.ts
Fixes ACX-851
Reload app on `ChunkLoadError`
=> fix: retry lazy load on `ChunkLoadError`

src/utils/notify.ts, src/views/Bridge/hooks/useBridgeAction.ts, src/views/Bridge/hooks/useBridgeDepositTracking.ts
This PR removes the edge case outlined in ACX-852. Additionally, this PR includes a reset of the `finishedDate` state when a user begins to attempt another bridge request in one session.
=> fix: remove edge case

src/components/WalletBalanceTrace/useWalletBalanceTrace.ts
In an effort to fix the Amplitude issue with the wallet balances, we track fetching errors on Sentry.
=> chore: track usd wallet balance errors

src/views/Bridge/Bridge.tsx, src/views/Bridge/components/BridgeForm.tsx, src/views/Bridge/components/InsufficientLiquidityAlert.tsx, src/views/Bridge/hooks/useBridge.ts
This adds an error message to the button disable in #677.
=> fix: add insufficient liquidity alert

src/utils/format.ts, src/views/Splash/hooks/useSplash.ts
Sets the total fidelity of the volume on the splash page to use one decimal of rounding
Closes: ACX-998
Closes: ACX-994
=> fix: :art: set rounding to one decimal place

api/_utils.ts, api/available-routes.ts, api/limits.ts, api/suggested-fees.ts, src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json, src/data/routes_5_0x0e2817C49698cc0874204AeDf7c72Be2Bb7fCD5d.json
This PR adds support for v2.5 Goerli testnet deployment in the serverless API.
=> feat(vercel): goerli testnet deployments + adjustments

.env.example, src/utils/config.ts, src/utils/constants.ts, src/views/Bridge/hooks/useBridge.ts
Closes ACX-1100
Allows us to enable USDT in the API but disable temporarily in the UI
=> feat: add config to disable bridge tokens in the ui

api/_constants.ts, src/components/RewardTable/RewardTables.styles.tsx, src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json, src/views/Referrals/comp/RewardTable/createMyReferralsTableJSX.tsx
Adds support for USDT bridging. Closes ACX-1064 and ACX-1063.
Requires https://github.com/across-protocol/frontend-v2/pull/731 and disabled USDT for bridging before merging.
=> feat: add USDT support

src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json
=> fix: usdt route arbitrum -> polygon

src/utils/notify.ts
=> fix: tx resolve on polygon deposit

src/utils/notify.ts
True fix for https://github.com/across-protocol/frontend-v2/pull/734
=> fix: notify emitter on supported chains

src/utils/constants.ts
Move up BAL position in token and pool selectors
=> feat: move BAL position

src/components/Selector/Selector.tsx, src/components/Tooltip/Tooltip.tsx, src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json, src/utils/constants.ts, src/views/Bridge/components/BridgeForm.tsx, src/views/Bridge/components/CoinSelector.tsx, src/views/Bridge/components/RouteNotSupportedTooltipText.tsx, src/views/Bridge/utils.ts, src/views/Referrals/comp/StepperWithTooltips/useStepperWithTooltips.tsx, vite.config.js
=> fix: info on usdc/usdc.e on arbitrum

src/views/Bridge/utils.ts
=> fix: only show ETH as receive token if dst not polygon

src/assets/grayscale-logos/zksync.svg, src/views/Bridge/components/DepositConfirmation.tsx
=> fix: deposit confirmation logo animation zkSync

src/views/Bridge/components/EstimatedTable.tsx
=> fix: add tooltip id to eth/weth info icon

api/suggested-fees.ts
- Never quote on future timestamps.
- If the user supplied a timestamp, don't modify it.
- Optimise by resolving the current block simultaneously with the token
details.
Closes ACX-1481
=> fix(suggested-fees): Quote timestamp handling

api/_constants.ts, api/_utils.ts, api/pools-list.ts
=> feat: add /pools-list endpoint

api/_constants.ts, api/_types/index.ts, api/_types/utility.types.ts, api/_utils.ts
This PR uses defillama for resolving Pool APY data for our balancer pools.
=> feat: use defillama for pool apy

src/views/Bridge/hooks/useSelectRoute.ts, src/views/Bridge/utils.ts
Allows setting query params on the /bridge page for pre-selected routes.
=> fix(bridge): allow from/to/token search params on bridge page

package.json, src/components/Sidebar/Sidebar.styles.tsx, src/components/Sidebar/Sidebar.tsx, yarn.lock
Updates sidebar lib hoping that this will fix https://linear.app/uma/issue/ACX-1275/landing-page-menu-button-doesnt-respond-on-click.
Initial tests confirm a performance boost
=> feat: bump react-pro-sidebar and refactor

src/utils/bridge.ts
Change est. time string for slow fills
=> fix: change slow fill est. time to 2-4 h

src/components/RewardTable/RewardTables.styles.tsx, src/components/Table/Table.styles.tsx, src/views/Rewards/components/GenericStakingPoolTable/GenericStakingPoolTable.styles.tsx, src/views/Staking/components/StakingInputBlock/StakingInputBlock.styles.tsx
Fixes ACX-1277, fixes ACX-1284 and ACX-1276
=> fix: table styles mobile rewards page

src/components/Pagination/Pagination.styles.tsx, src/components/Pagination/PaginationExample.tsx, src/views/Transactions/components/SpeedUpModal/InputWithButton.tsx, src/views/Transactions/components/SpeedUpModal/SpeedUpModal.styles.tsx, src/views/Transactions/components/SpeedUpModal/SpeedUpModal.tsx, src/views/Transactions/components/SpeedUpModal/SpeedUpStats.tsx, src/views/Transactions/components/TransactionsTable/TransactionsTable.styles.tsx
Fixes various issues on the transactions page for mobile. Fixes ACX-1279, ACX-1280 and ACX-1281
=> fix: transactions page mobile fixes

src/views/Bridge/components/AmountInput.tsx, src/views/Bridge/components/DepositConfirmation.tsx, src/views/Bridge/hooks/useBridgeDepositTracking.ts
=> fix: bridge page mobile issues

src/utils/amplitude.ts, src/utils/constants.ts, src/views/Bridge/hooks/useBridge.ts, src/views/Bridge/hooks/useBridgeAction.ts, src/views/Bridge/hooks/useTransferQuote.ts
Try to fix ACX-1583
This PR removes some of `useEffect`s prone to race conditions and replaces them with a `useQuery`.
=> fix: make quotes fees less prone to race conditions

api/_constants.ts
**Overview**
Testers, use the following templates to pass the pull request or to report issues that require a resolution.
Following these guidelines will help the developer respond more quickly to issues, but you are free to comment
in any way as needed to help resolve issues.
**Reporting QA Issues**
Testers should use Github comments to report issues with the PR. Use screenshots if relevant, you can also
check the [developer console](https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console)
to see if there are any logs which might be related. Use the following template when reporting a problem or issue with the PR.
You submit multiple comments using this template if there are multiple issues.
```
**QA Issue**
**Repro Steps** …
```
=> improve: Add ACX, BAL, POOL capital costs config

.env.example, api/_utils.ts, api/available-routes.ts, api/token-list.ts, src/utils/config.ts, src/utils/constants.ts, src/views/Transactions/utils.ts
This adds token whitelisting to available routes / token routes endpoints.
=> improve: whitelist tokens from available endpoint

src/components/Tooltip/Tooltip.styles.tsx, src/components/Tooltip/Tooltip.tsx, src/views/DepositStatus/hooks/useDepositTracking.ts
=> fix: tooltip opacity + deposit tx tracking

src/views/DepositStatus/components/DepositStatusLowerCard.tsx
=> improve: include referral CTA in deposit status

src/Routes.tsx, src/hooks/useRewardSummary.ts, src/hooks/useRewardToken.ts, src/hooks/useSimplifiedReferralSummary.ts, src/utils/constants.ts, src/views/Bridge/components/BridgeForm.tsx, src/views/Bridge/components/ReferralCTA.tsx, src/views/DepositStatus/components/DepositStatusLowerCard.tsx, src/views/Rewards/hooks/useRewardProgramCard.ts, src/views/Rewards/hooks/useRewards.ts, src/views/RewardsProgram/ACXReferralsProgram.tsx, src/views/RewardsProgram/GenericRewardsProgram/GenericCard.tsx, src/views/RewardsProgram/GenericRewardsProgram/GenericEmptyTable.tsx, src/views/RewardsProgram/GenericRewardsProgram/GenericRewardsProgram.tsx, src/views/RewardsProgram/OPRebatesProgram.tsx, src/views/RewardsProgram/hooks/useACXReferralsProgram.ts, src/views/RewardsProgram/hooks/useGenericRewardClaimCard.ts, src/views/RewardsProgram/hooks/useOPRebatesProgram.ts
This PR adds the frame to track OP rebates rewards.
=> feat: add OP rewards page

src/views/RewardsProgram/GenericRewardsProgram/GenericRewardsProgram.tsx
Fixes a bug where the user cannot see the dropdown column when looking to resize a page.
Closes ACX-1735
=> fix: resolve ui dropdown

src/hooks/useStakingPool.ts, src/utils/config.ts, src/utils/staking-pool.ts, src/views/LiquidityPool/LiquidityPool.tsx, src/views/LiquidityPool/hooks/useUserLiquidityPool.ts
This PR allows withdrawing from the Boba Liquidity Pool. There was a regression when the pool itself was disabled, but this has now been corrected.
=> fix: allow boba withdrawal

package.json, yarn.lock
This is an initial push to get this dependency onto our FE while being compliant with dependency review.
=> feat: add vercel/kv dependency

package.json, yarn.lock
This includes a fix for gas pricing on Base.
=> chore: Bump sdk-v2

src/views/Staking/components/StakingExitAction/StakingExitAction.styles.tsx, src/views/Staking/components/StakingExitAction/StakingExitAction.tsx
Resolve the UI bug when two tokens are displayed next to one another - only visible on the wrapped staked eth/ acx
=> fix: resolve wsteth/acx staking pool

scripts/generate-routes.ts, src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json, src/utils/constants.ts, src/views/Bridge/components/RouteNotSupportedTooltipText.tsx, src/views/Bridge/utils.ts
=> fix: correctly label usdc.e for polygon

package.json, scripts/generate-routes.ts, src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json, src/data/routes_5_0x0e2817C49698cc0874204AeDf7c72Be2Bb7fCD5d.json, yarn.lock
=> feat: enable dai on zksync

src/utils/constants.ts, src/utils/serverless-api/prod/coingecko.ts, src/utils/serverless-api/prod/pools.ts, src/utils/serverless-api/prod/retrieveLimits.ts, src/utils/serverless-api/prod/suggested-fees.prod.ts, vercel.json
This enables CORS for our Vercel API. Also allow overriding the Vercel API endpoint via env var.
=> feat: enable CORS in api

src/views/DepositStatus/hooks/useDepositTracking.ts
This fixes the instrumentation of the `TrasferCompleted` events on Amplitude. We observed some edge cases where the event was attributed with a user id of `none`. This enforces the existence of a connected wallet
=> fix(ampli): transfer deposit completed event

package.json, src/utils/deposits.ts, src/utils/typechain.ts, yarn.lock
This PR accounts for the V3 events when a user wishes to check their deposit confirmation status. This is backward compatible with V2 events
=> feat(v3): funds deposited for V3 events

api/suggested-fees.ts
=> feat: Account for possibility that relayer takes repayment on mainnet

src/ampli/index.ts, src/utils/amplitude.ts
Pathname routes for page lookups are now sanitized.
=> fix: amplitude page tracking

api/_utils.ts
Spurred by https://github.com/across-protocol/frontend-v2/pull/980/files#r1518357166
=> improve(V3): simulate relay with V3 fn

src/views/Bridge/components/AmountInput.tsx
https://github.com/across-protocol/frontend-v2/pull/984#pullrequestreview-1937005742
=> fix: disable auto incrementing/decrementing on scroll

api/_constants.ts
This reverts commit cc6e3a0f9a5324ebb5d5c6423b31e165bec07534.
=> Revert "fix(snx relayer): temporarily move relayer support (#988)"

api/_constants.ts
Submitted for approval in advance of Synthetix updating their bot.
This reverts commit c2f8fd5304f6d2f95ac330049015269d6f28661c.
=> Revert "fix(snx relayer): temporarily move relayer support (#990)"

.env.example, api/_utils.ts, package.json, scripts/generate-routes.ts, src/assets/grayscale-logos/linea.svg, src/assets/linea-logo.svg, src/components/Selector/Selector.tsx, src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json, src/utils/constants.ts, src/views/DepositStatus/components/DepositStatusUpperCard.tsx, yarn.lock
Closes ACX-1778 and ACX-1777
Keeping as a draft until tested
=> feat(linea): add support for linea

src/utils/bridge.ts, src/utils/fill-times.ts
=> feat: more accurate fast fill time estimations

api/suggested-fees.ts
=> refactor(api): put rate model rpc call into multicall

src/views/Transactions/Transactions.tsx
=> fix: use full display width for tx table

api-docs-openapi.yaml
This PR adds the OpenAPI yaml file for our API docs. We also updated the docs according to the changes made here https://github.com/across-protocol/frontend-v3/pull/1013. I opted to open a separate PR to not further increase the diff.
=> docs: add openapi yaml file for api docs

src/components/DepositsTable/cells/NetFeeCell.tsx, src/hooks/useDeposits.ts
=> feat: add swap fees to breakdown

src/utils/config.ts
=> fix: get token list

src/hooks/useSwapQuote.ts
Swap quote needs to be updated more frequently
=> fix: update swap quote more aggressively

api/_utils.ts, package.json, yarn.lock
Bumps the SDK and changes how we call instantiate queries
=> chore: bump sdk

api-docs-openapi.yaml
=> docs: fix api examples

package.json, yarn.lock
Introduces updated fee logic https://github.com/across-protocol/sdk-v3/commit/25c5cd781bc0c80e53688d5d5a66adfc31b50301
=> fix: pool fees

src/views/Bridge/hooks/useTransferQuote.ts
Fixes bug when recipient address was not updated correctly
=> fix: not updated recipient address

api-docs-openapi.yaml
Add `x-codeSamples` and fix schema
=> docs: fix docs fees schema and try it

vercel.json
Rewrite the indexer service to be the serverless API
=> chore: add rewrite

api-docs-openapi.yaml
Adds the recently added `/deposit/status` endpoint
=> feat(openapi): add deposit/status

api-docs-openapi.yaml
Update docs to include a more representative chain id / deposit id
=> nit: docs change

api-docs-openapi.yaml
Adds new fields to `deposit/status` endpoint
=> chore: update api docs

api-docs-openapi.yaml
We need to wrap `example + $ref` in an `allOf` statement.
=> fix: documentation

api-docs-openapi.yaml
No one should be using this parameter
**Overview**
Testers, use the following templates to pass the pull request or to report issues that require a resolution.
Following these guidelines will help the developer respond more quickly to issues, but you are free to comment
in any way as needed to help resolve issues.
**Reporting QA Issues**
Testers should use Github comments to report issues with the PR. Use screenshots if relevant, you can also
check the [developer console](https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console)
to see if there are any logs which might be related. Use the following template when reporting a problem or issue with the PR.
You submit multiple comments using this template if there are multiple issues. …
=> feat(api-docs): Deprecate `token` parameter in docs

api/_constants.ts, api/_utils.ts, api/limits.ts, api/suggested-fees.ts, src/views/Bridge/Bridge.tsx, src/views/Bridge/components/BridgeForm.tsx, src/views/Bridge/hooks/useBridge.ts
Refine default limits buffer multipliers and logic
=> refactor(limits): refine buffer logic and default values

api-docs-openapi.yaml
=> improve(api-docs): Remove comments about deprecation of `token`

src/hooks/useDeposits.ts, src/utils/local-deposits.ts
The handling of optimistically added deposits to local storage was a bit broken. This PR improves the handling
=> fix: improve optimistically added local deposits

package.json, src/utils/onboard.ts, yarn.lock
Bump version of onboard module to include more robust EIP-6963 support
=> improve(eip-6963): include more robust support

api/swap-quote.ts, src/components/Tooltip/Tooltip.styles.tsx, src/components/Tooltip/Tooltip.tsx, src/hooks/useSwapQuote.ts, src/views/Bridge/components/BridgeForm.tsx, src/views/Bridge/components/EstimatedTable.tsx, src/views/Bridge/components/FeesCollapsible.tsx, src/views/Bridge/hooks/useBridge.ts, src/views/Bridge/utils.ts
=> feat: swap price impact warning

src/views/Bridge/components/EstimatedTable.tsx
Updates copy on the fee estimation table. Will affect the bridge and deposit confirmation pages.
=> chore: copy change

src/data/fill-times-preset.json, src/utils/fill-times.ts
=> chore: update fill times

api/_constants.ts, scripts/chain-configs/lisk/index.ts, scripts/generate-routes.ts, src/constants/chains/index.ts, src/data/routes_11155111_0x14224e63716afAcE30C9a417E0542281869f7d9e.json, src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json
=> feat: add lisk chain support

scripts/chain-configs/mode/index.ts, src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json
We missed enabling some deposit routes when adding Mode.
=> feat: enable WBTC mode <-> arb

scripts/chain-configs/arbitrum/index.ts, scripts/chain-configs/base/index.ts, scripts/chain-configs/linea/index.ts, scripts/chain-configs/lisk/index.ts, scripts/chain-configs/mainnet/index.ts, scripts/chain-configs/mode/index.ts, scripts/chain-configs/optimism/index.ts, scripts/chain-configs/polygon/index.ts, scripts/chain-configs/zk-sync/index.ts, scripts/generate-ui-assets.ts, src/constants/chains/configs.ts, src/views/DepositStatus/hooks/useDepositTracking.ts
Fixes ACX-2431
Improves UX for fills that take a bit longer on the deposit status screen.
=> refactor: use constant retry delay for deposit status tracking

src/ampli/index.ts, src/hooks/useRouteTrace.ts, src/views/Bridge/hooks/useBridgeAction.ts
Complimentary PR to across.to PR to track siteUrl in page view events
=> feat(analytics): track page views with site url

src/views/Bridge/hooks/useBridgeAction.ts
=> fix: integrator query param in bridge action

api-docs-openapi.yaml, src/hooks/useReferrer.ts, src/utils/bridge.ts, src/utils/format.ts, src/views/Bridge/hooks/useBridgeAction.ts
This PR allows custom tracking of domain ids when a user includes the `?integrator_id` query param.
=> feat(analytics): track custom domain identifier

README.md, api/_utils.ts, api/batch-account-balance.ts, package.json
=> fetch batch balances

scripts/chain-configs/zora/assets/grayscale-logo.svg, scripts/chain-configs/zora/assets/logo.svg, src/assets/chain-logos/zora-grayscale.svg
=> add animate ids to zora icons

src/utils/bridge.ts
=> enable depositExclusive

src/assets/chain-logos/zora-grayscale.svg, src/views/DepositStatus/components/DepositStatusUpperCard.tsx
=> fix: infer root color, set stop opacity

scripts/chain-configs/arbitrum/index.ts, scripts/chain-configs/base/index.ts, scripts/chain-configs/optimism/index.ts, scripts/chain-configs/polygon/index.ts, scripts/chain-configs/types.ts, scripts/generate-chain-config.ts, scripts/generate-routes.ts, src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json
- Adds missing bridged USDC -> USDzC swap routes
- Refactors routes generation script for handling swap routes + bridged USDC routes
=> fix: routes generation script  + add usdzc swap routes

api/batch-account-balance.ts
=> Fix: handle single addresses in batch handler

api/_timings.ts, api/suggested-fees.ts
=> feat: allow rebalance timing override

src/components/Sidebar/useSidebar.ts
Add ToS to navbar.
Waiting for https://github.com/across-protocol/across.to/pull/58 to be merged
=> improve: add tos nav link

.gitignore, api/_exclusivity/config.ts, api/_exclusivity/index.ts, api/_exclusivity/strategies/index.ts, api/_exclusivity/strategies/weighted-random.ts, api/suggested-fees.ts, scripts/pre-build.ts, scripts/remote-configs/utils.ts, src/data/examples/exclusivity-strategy.json
=> feat: make exclusivity strategy selection configurable

api/_utils.ts, api/limits.ts
=> feat: use retry provider in api

api/_exclusivity/index.ts
depositExclusive() is not yet available on all SpokePools. It should be available later today.
=> fix(exlcusivity): Reintroduce origin chain constraint

api/_utils.ts, api/limits.ts, package.json, yarn.lock
This reverts commit 3d5cf53b544b31da8d75a419eba148f651683c20.
Need to revert for now. There are still some 500s that I need to resolve. And I want to unblock other PRs
=> Revert "perf: api speed improvements (#1194)"

src/views/Bridge/hooks/useBridgeAction.ts
This permits exclusivity to be applied on ETH deposits as well.
=> improve(exclusivity): Route exclusive ETH deposits via SpokePool

src/utils/constants.ts, src/views/Bridge/components/BridgeForm.tsx, src/views/Bridge/hooks/useEstimatedRewards.ts
=> chore: remove arb rewards

.github/actions/setup/action.yaml, .nvmrc, README.md, api/_utils.ts, api/limits.ts, api/suggested-fees.ts, package.json, yarn.lock
=> perf: improve api speed by caching gas units + speed provider

api/_errors.ts
Return the attempted transaction object as part of the SimulationError API response for easier debugging via tools like Tenderly
=> feat: add `transaction` to sim error api response

api/limits.ts
Using cached gas prices still seems to be not correct. Reverting for now
=> fix: revert using cached gas price

api/_utils.ts, api/cron-cache-gas-prices.ts, api/limits.ts
Fixes bug from #1224 by caching the correct gas price for OP stack chains
=> fix: op stack cached gas price

src/views/DepositStatus/hooks/useDepositTracking.ts
Try to minimize discrepancies between perceived deposit/fill times and real times
=> fix: decrease deposit status retry delay

api/_utils.ts
We don't use GCP logging for our production logs; instead, we use Datadog with log drains from Vercel. Therefore, this PR removes the dependency for now.
I also want to exclude the possibility that this logger might create issues with the new default streaming behavior of serverless functions in the context of ACX-2854
=> fix: remove gcp logger

api/_utils.ts
Temp. disable API logger on Vercel in production
=> fix: temp disable logger in api

api/_timings.ts
This reverts commit 15f264996f7510d328aff6164a5111ab08d8c7c0.
No impact
=> Revert "fix: revert fill time refactor to test perf impact (#1235)"

src/utils/constants.ts
=> feat: enable op rebates world chain

api/cron-cache-gas-prices.ts
=> fix: cron cache gas prices

README.md, scripts/chain-configs/arbitrum-sepolia/index.ts, src/data/chains_11155111.json, src/data/routes_11155111_0x14224e63716afAcE30C9a417E0542281869f7d9e.json
Requested by an integrator for testing.
=> improve: Support USDC on Arbitrum Sepolia

api/cron-cache-gas-prices.ts
Reverting gas price smoothing due to its potential to produce waves of unprofitable deposits, especially destined for mainnet
=> fix: revert gas price smoothing

api/cron-cache-balances.ts, package.json, yarn.lock
Cron job was failing due to missing World Chain Mulicall3 address. Fixed via SDK update
=> fix: worldchain cron cache balances

scripts/chain-configs/arbitrum-sepolia/index.ts, scripts/chain-configs/arbitrum/index.ts, scripts/chain-configs/base-sepolia/index.ts, scripts/chain-configs/base/index.ts, scripts/chain-configs/blast-sepolia/index.ts, scripts/chain-configs/blast/index.ts, scripts/chain-configs/linea/index.ts, scripts/chain-configs/lisk-sepolia/index.ts, scripts/chain-configs/lisk/index.ts, scripts/chain-configs/mainnet/index.ts, scripts/chain-configs/mode-sepolia/index.ts, scripts/chain-configs/mode/index.ts, scripts/chain-configs/optimism-sepolia/index.ts, scripts/chain-configs/optimism/index.ts, scripts/chain-configs/polygon-amoy/index.ts, scripts/chain-configs/polygon/index.ts, scripts/chain-configs/redstone/index.ts, scripts/chain-configs/scroll/index.ts, scripts/chain-configs/sepolia/index.ts, scripts/chain-configs/types.ts, scripts/chain-configs/world-chain/index.ts, scripts/chain-configs/zk-sync/index.ts, scripts/chain-configs/zora/index.ts, scripts/generate-chain-config.ts, scripts/generate-routes.ts, src/data/chains_1.json, src/data/chains_11155111.json
This might be useful in the app-sdk for retrieving lower bound `fromBlock` values when fetching logs
=> feat: add `SpokePool` deployment block to `/chain`

api/_cache.ts
Improve required KV/Redis env vars
=> fix: required kv env vars

api/_cache.ts
I had to handle Upstash env vars separately because Vercel won't let me override the reserved system env vars without deleting the existing storage. Therefore using the approach of this PR
=> fix: separate upstash redis env vars

api/_errors.ts
Improve API logs - this will allow us to build better dashboards on Datadog
=> feat: add api error code to log

src/utils/constants.ts
~~We may need to wait for the scraper for this. cc @amateima~~
Given the go-ahead from @melisaguevara
=> feat: add lisk to op rewards estimation

package.json, src/components/Wallet/Web3Subscribe.tsx, src/utils/onboard.ts, yarn.lock
=> feat: coinbase smart wallet

api/suggested-fees.ts
=> fix: only cache fees response if exclusive

api/_dexes/cross-swap.ts, api/_dexes/types.ts, api/_dexes/uniswap.ts, api/_dexes/utils.ts, api/_multicall-handler.ts, api/_utils.ts, api/swap-quote.ts, api/swap.ts, scripts/tests/swap.ts
=> feat: uniswap min output cross swap quotes resolver

api/_dexes/cross-swap.ts
Skip SpokePoolVerifier-flow until unified periphery contract audited + deployed
=> feat: skip spokepool verifier temp

src/hooks/useIndexerDepositTracking.ts, src/utils/constants.ts, src/views/Transactions/components/PersonalTransactions.tsx
This PR adds preliminary deposit tracking for load testing the indexer with requests.
=> feat(indexer): include deposit tracking for load testing

api/cron-ping-endpoints.ts, vercel.json
Closes ACX-3387
This needs to merged into prod bc we only have cron enabled there
=> feat: cron job to keep endpoints hot

api/_utils.ts
=> set default limit multiplier to 80%

api/_dexes/cross-swap.ts, api/_utils.ts, api/swap/_utils.ts, api/swap/allowance.ts, package.json, yarn.lock
- measure full running time of swap/allowance endpoint (add requests data as well as `crossSwapQuotes`).
- measure running time `getCrossSwapQuotes`, we can separate these by `amountType` eg, "exactInput" | "exactOutput".
- measure time to get crossSwapQuote by crossSwapType. eg "b2b" | "b2a" etc.
=> measure swap/allowance performance

src/components/DepositsTable/cells/AddressCell.tsx, src/components/Sidebar/useSidebar.ts, src/components/Wallet/Wallet.tsx, src/hooks/useEns.ts
We were previously relying on onboard to generate our ENS addresses. This is no longer reliable.
=> fix: use more accurate ENS

package.json, yarn.lock
=> chore: patch secp256k1

src/Routes.tsx, src/utils/constants.ts, src/views/Bridge/utils.ts
Generates custom urls for each destination chain
=> feat: dynamically render custom bridge pages

api/_exclusivity/index.ts, api/suggested-fees.ts
Enables the use of relay fill configurations in the suggested-fees API endpoint.
=> feat: use exclusivity configuration in suggested fees

package.json, scripts/chain-configs/lisk/index.ts, scripts/chain-configs/world-chain/index.ts, src/data/chains_1.json, src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json, yarn.lock
WBTC on Lisk & POOL on World Chain.
=> chore: Enable new tokens

api/_dexes/uniswap/quote-resolver.ts, api/_dexes/uniswap/swap-router-02.ts, api/_dexes/uniswap/trading-api.ts
=> perf: use indicative quotes as guesstimates

api/limits.ts
Hardcodes the behavior of our ZKSync paths from L1 -> ZKSync. See slack.
=> chore(zksync): update zksync limits

api/_permit.ts, api/_transfer-with-auth.ts, api/swap/index.ts, api/swap/permit/index.ts
=> feat: unified swap endpoint

package.json, yarn.lock
- Applies `priorityFeeMultiplier` to Linea's priority fee rather than the `baseFeeMultiplier`
- Allows caller to set a floor on any EIP1559's `priorityFee` with a default of 0.5 gwei for chainId=1 hardcoded
=> improve(API): Use newer SDK version for updated gas price oracle logic

api/_utils.ts, api/limits.ts
A slight clean up to simplify existing logic
=> improve(api): make buffer cap logic more intuitive

api/_errors.ts, api/limits.ts
Log cause for better debugging
=> chore: improve error log 

src/views/Bridge/components/ChainSelector.tsx
Across currently does not support same-chain bridging. This change filters external projects out when they appear as an origin/destination to the intermediary chain.
I.e. if you have Arbitrum selected in the origin chain you should not see Hyperliquid as a destination. If you have Hyperliquid selected on the destination you shouldn't see Arbitrum as an option in the origin.
=> improve: don't show intermediary route as potential option

api/suggested-fees.ts
This reverts commit 28dcea6d875f3846fbed469ef252f64a3a801ac4.
=> Revert "chore: deprecate legacy fee response values (#1307)"

package.json, yarn.lock
Relevant updates are:
- removing the need to specify NEW_GAS_PRICE_ORACLE or EIP1559_GAS_PRICE_ORACLE_RAW env vars
=> feat: Update SDK, Contracts and Constants

api/_exclusivity/strategies/weighted-random.ts
This PR changes the default relayer weight to 0.
=> ENH: Set default relayer weight to 0

api/_address.ts, api/_utils.ts, package.json, test/api/_utils.test.ts, yarn.lock
Adds validation for SVM addresses to use throughout the api and app
=> Add validation or SVM addresses

api-docs-openapi.yaml
Adding 2 more status enums that i have observed while using the status api.
=> fix: add refunded and slowFillRequested status

api/_dexes/cross-swap-service.ts, api/_dexes/utils.ts, api/_utils.ts, api/swap/_utils.ts, scripts/tests/_swap-utils.ts
Closes ACX-3297
~Based #1496, therefore draft until base PR merged.~
Example transactions
| Type | Origin tx | Destination tx |
|- |-|- |
| Direct bridging: USDC (Op) - USDC (Arb) | [Tx](https://optimistic.etherscan.io/tx/0xae2b02dfdb3f451dd224cb1095a1a7fca659a39c88267a512474b4e71ffec341) | [Tx](https://arbiscan.io/tx/0x71a3da6c070e0929f70931fdedbb539bf5be6c03a73314a0d771ae7ffd7782d4) |
| Direct briding with unwrap: ETH (Op) - ETH (Arb) | [Tx](https://optimistic.etherscan.io/tx/0x8920dcaff95e5a9a9e59d0900457c7956c36d9e60cbd698da1b8892776138a32) | [Tx](https://arbiscan.io/tx/0xb2225fbfea3a33f8d810020f675308efd9efd7824d5bc64e31ba1ff2e2d29484) |
Bridge + destination swap: USDC (Op) - APE (Arb) | [Tx](https://optimistic.etherscan.io/tx/0x94831e5d128cb7e2cca19b947ce6ceca1ffe5d20a3853469c5bcb623 …
=> feat: support exact input amount type

api/limits.ts
=> improve: allow slow fills on POOL via the FE

api/rpc-proxy.ts, src/constants/chains/configs.ts, src/constants/chains/utils.ts, src/utils/providers.ts
Let's the frontend use the proxy rpc for lens without the internal auth token.
=> Whitelist frontend for proxy rpc

src/views/Bridge/hooks/useTransferQuote.ts
=> feat: allow universal swap quote retrieval not-connected

src/utils/constants.ts
=> fix: universal swap routes sepolia

api/_constants.ts
=> chore: Update USDC capital fee

scripts/generate-swap-routes.ts, src/data/universal-swap-routes_1.json
=> chore: disable lens gho -> l1 lgho

vercel.json
This is already part of master but we also want to be able to query it using this deployment url.
=> chore: enable deposits endpoint

api/_balance.ts, api/_constants.ts, api/_fill-deadline.ts, api/_gas.ts, api/_logger.ts, api/_multicall.ts, api/_providers.ts, api/_recipient-address.ts, api/_relayer-address.ts, api/_spoke-pool.ts, api/_utils.ts, api/batch-account-balance.ts, api/coingecko.ts, api/cron-cache-balances.ts, api/cron-cache-gas-costs.ts, api/cron-cache-gas-prices.ts, api/cron-cache-l1-data-fee.ts, api/gas-prices.ts, api/limits.ts, api/suggested-fees.ts, api/swap/approval/_service.ts, package.json, src/utils/sdk.ts, src/views/Bridge/hooks/useBridgeAction_new/strategies/svm.ts, yarn.lock
=> feat(api): support svm

api/_utils.ts
=> fix: scale output amount for deposit with message

api/_utils.ts
This reverts commit 90095c8fce1d68925ed5b6d162f197c0e795fce9.
=> Revert "fix: scale output amount for deposit with message (#1606)"

api/_fill-deadline.ts, api/_providers.ts, api/_utils.ts, src/utils/bignumber.ts, src/utils/deposits.ts, src/utils/sdk.ts, src/views/Bridge/hooks/useBridgeAction/strategies/svm.ts
Cherry picked some fixes some this [PR](https://github.com/across-protocol/frontend/pull/1586)
=> Fixes filldeadline & empty message for deposits to Solana

src/Routes.tsx, src/assets/icons/arrow-right.svg, src/assets/icons/solana-with-bg.svg, src/components/Banner/Banner.styles.tsx, src/components/Banner/Banner.tsx, src/components/Banners/index.tsx
=> feat: solana featured bridge route banner

api/_dexes/cross-swap-service.ts, api/_dexes/utils.ts, api/_utils.ts, test/api/_dexes/utils.test.ts
Reverts across-protocol/frontend#1661
=> Revert "feat: select best quote based on all possible cross swap types"

api/_dexes/0x/allowance-holder.ts, api/_dexes/cross-swap-service.ts, api/_dexes/gho/multicall.ts, api/_dexes/gho/wrapped-gho.ts, api/_dexes/lifi/lifi-router.ts, api/_dexes/types.ts, api/_dexes/uniswap/swap-router-02.ts, api/_dexes/uniswap/universal-router.ts, api/_dexes/uniswap/utils/v3-sdk.ts, api/_dexes/utils.ts, api/_errors.ts, api/_utils.ts, api/suggested-fees.ts, api/swap/_utils.ts, api/swap/approval/_service.ts, api/swap/approval/_utils.ts, api/swap/approval/index.ts, instrumentation.ts, scripts/tests/_swap-utils.ts, scripts/tests/swap.ts
This PR contains various tweaks and fixes for issues that came up during testing. I will leave some comments in the diff so that you can better understand the reasoning behind the changes. I know that it might be better to split this PR up into multiple smaller ones. So if it is too hard to understand the changes let me know
=> fix: misc cross swap service improvements

api/_dexes/0x/allowance-holder.ts, api/_errors.ts, api/swap/_utils.ts, api/swap/approval/_service.ts, scripts/tests/_swap-utils.ts
Various smaller fixes and improvements for better error handling, monitoring and correct responses
=> fix(swap): misc error improvements and fixes

api/_dexes/0x/utils/sources.ts, api/_dexes/lifi/utils/sources.ts, scripts/generate-dex-sources.ts
=> feat: re-gen sources + support excluding sources

api/swap/sources.ts
Noticed we were not handling this error while testing.
=> fix: handle invalid chain when requesting sources

scripts/chain-configs/solana/index.ts, scripts/chain-configs/types.ts, scripts/generate-routes.ts, src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json, src/views/Bridge/components/ChainSelector.tsx, src/views/Bridge/hooks/useBridgeAction/strategies/abstract.ts, src/views/Bridge/hooks/useBridgeAction/strategies/evm.ts, src/views/Bridge/hooks/useBridgeAction/strategies/svm.ts
closes ACP-2
- Ensure we switch back to origin chain after signing message on Arbitrum
- Move logic, since this is evm only.
=> fix: EVM => Hyperliquid

api/_dexes/cross-swap-service.ts, scripts/tests/swap-quotes.ts
We didn't correctly select a matching strategy for A2A flows. This was uncovered because we now have >1 strategies that support `sellEntireBalance`.
=> fix: matching strategy selection a2a

api/suggested-fees.ts
=> fix: required `recipient` query param if dst is svm

api/_dexes/0x/utils/sources.ts, api/_dexes/lifi/lifi-router.ts, api/_dexes/lifi/utils/sources.ts, api/_dexes/uniswap/universal-router-02.ts, api/_dexes/uniswap/utils/sources.ts, api/_errors.ts, api/swap/_configs.ts, api/swap/sources.ts, package.json
- Regenerate DEX sources
- Include Uniswap API sources to `/swap/sources` endpoint
- Bump Uniswap API prio
- Tweak LiFi API speed
- Improve upstream RPC error
=> chore: re-gen dex sources + tweaks

api/_dexes/0x/utils/sources.ts, api/_dexes/lifi/utils/sources.ts, api/cron-cache-l1-token-configs.ts, api/cron-ping-endpoints.ts
I noticed the other a few error codes that we didn't fix in a while related to some cron jobs
=> fix: cron jobs for l1 token configs + pinger

api/_dexes/lifi/utils/sources.ts, api/swap/_utils.ts
Adds try/catch to validate functionSignature/ABI
=> fix: improve `AbiEncodingError` handling

api/_balance.ts, api/_providers.ts
=> perf: use speed provider in /batch-account-balance

scripts/tests/_swap-utils.ts, scripts/tests/swap.ts
Closes ACX-4342
Test tx that was created with local changes to support B2B SVM -> EVM
- https://solscan.io/tx/3VmFL87PYXHwn9j35C6uEsf7bA6gMk661yrFaj8ki81CJ3ovddyV87KSq38VeDwYuV8nX1XyxeyFfT4uthsb8k5N
=> feat: support svm in swap test script

api/_cache.ts, api/_dexes/utils.ts, api/_fill-deadline.ts, api/_providers.ts, api/_utils.ts, api/build-deposit-tx.ts, api/suggested-fees.ts
Reverts across-protocol/frontend#1693
=> Revert "feat: reduce RPC usage in API"

api/swap/approval/_utils.ts
Appends Swap API marker to SVM memo data.
[Example tx](https://solscan.io/tx/24N9kEG6ujwymryQmEavevLn4i681DwNCD8wuKbNtx8i3XWxBS3j5GL3Nmgy8qPFCuxZrNg3zjLTeyzmQzVhXEyQ)
=> feat: tag svm origin swap api tx data

src/ampli/index.ts, src/views/DepositStatus/components/TwitterShare/TwitterShareCard.tsx, src/views/DepositStatus/components/TwitterShare/TwitterShareModal.tsx
- Added Amplitude tracking for share actions in TwitterShareCard and TwitterShareModal components.
- Updated event tracking interfaces to include new xShare section for various share actions.
=> feat: enhance Twitter sharing functionality with Amplitude tracking for xShare events

api/swap/tokens/index.ts
This PR adds Jupiter's tokens to the /swap/tokens endpoint response.
=> feat: add Solana tokens to /swap/tokens endpoint

CODEOWNERS
This PR adds me as a CODEOWNER to this repo.
=> chore: edit CODEOWNER

api/_utils.ts, e2e-api/swap/fetch-approval.test.ts, test/api/_utils.test.ts
Reverts across-protocol/frontend#1867
=> Revert "fix: incorrect token information in response for wetheth"
