- src/Routes.tsx
- src/components/SendForm/SendForm.tsx
- src/components/SendForm/useSendFormComponent.ts
- src/components/SuperHeader/SuperHeader.tsx
- src/hooks/useBridge.ts
- src/hooks/useError.tsx
- src/hooks/useSendForm.tsx
- src/utils/constants.ts
- src/utils/errors.ts
- src/views/Pool.tsx
- src/views/Send/Send.tsx
This PR refactors the error banner at the top of the app to work with the new state management logic.
Note: 
I tried a different implementation with React Portals where you could render the `SuperHeader` banner inside the `Send` view (in the React tree) but render on top of the header in the real html tree. 
I think it had a nicer API:
```javascript
function SomeSendComp() {
const {fromChain} = useSendForm();
return (
<>
<SuperHeader>{logic to show errors}</SuperHeader>
<OtherComp>...
)
```
But it was really slow, so I abandoned that approach for this one, were we sync the banner with `useEffects` , I don't love this solution, so open to ideas on how to improve on this
> fix(across-v2): make error banner work with new logic

- src/components/AddressSelection/AddressSelection.styles.ts
- src/components/CoinSelection/CoinSelection.styles.ts
- src/components/CoinSelection/CoinSelection.tsx
Story details: https://app.shortcut.com/uma-project/story/3405
1. The main feature added in this PR is showing the balance of the current selected token
But I also fixed some small issues I found:
2. Destination chain name was shown on multiple lines
3. Error box was occupying space if the form didn't have any error
> fix: add balance to coin selection

- src/hooks/useBridge.ts
- src/utils/bridge.ts
This PR fixes a timestamp issue, `quoteTimestamps` were taken as the block timestamp of the sending chain, but now this is fixed and `getCurrentTime` on the `HubPool` is used.
> fix(across-v2): take timestamp from hubpool

- src/components/SendAction/SendAction.tsx
- src/components/SendAction/useSendAction.ts
Signed-off-by: amateima <amatei@umaproject.org>
This PR adds an animation to the deposit button and also disables it while the deposit transaction is in pending state
> fix: add loading animation on deposit

- src/utils/constants.ts
Adds a fake hubpool mainnet address, to not crash the build until a real one is deployed
> fix(across-v2): add fake hubpool

- src/components/AddressSelection/AddressSelection.styles.ts
- src/components/AddressSelection/AddressSelection.tsx
- src/components/AddressSelection/useAddressSelection.ts
Signed-off-by: amateima <amatei@umaproject.org
Quick PR that allows the user to revert the destination address to the connected wallet  by allowing to pass an empty value
> fix: revert destination address by passing empty value

- src/Routes.tsx
- src/hooks/useSendForm.tsx
- src/utils/bridge.ts
Allows to pre-populate the send tab with the from and to chain from query params:
Example: `http://localhost:3000/bridge?from=288&to=1` would render a send tab from boba to mainnet
> feat(across-v2): add query params for bridge tab

- src/components/SendAction/useSendAction.ts
Fixes https://app.shortcut.com/uma-project/story/5238/send-button-is-enabled-while-a-deposit-is-pending
> fix(across-v2): disable send until tx confirms

- src/components/CoinSelection/useCoinSelection.tsx
- src/hooks/useBalance.ts
Fixes https://app.shortcut.com/uma-project/story/5204/incorrect-wallet-balances-showing-on-v2 by keeping the old query data until the new one arrives.
**Why the bug happened**
There was actually no bug, by default, react query will throw out the old data when the keys for a query change, since we use the block number as the query key, each time that changes, we consider it as a new query and we throw out old data. This has the effect of making the `balances` undefined until we get the fresh data.
Now, react-query will keep the previous balances until the fresh data arrives, and consequently, the UI will always show balances
> fix(across-v2): keep past data in balance queries

- src/utils/constants.ts
Spoke pool address did not match what the kovan hubpool said, points to correct spoke pool now.
> fix: wrong kovan weth spoke pool

- src/utils/ethers.ts
- src/utils/index.ts
- src/utils/tokenRoutes.ts
Adds a function to discover all supported tokens/spoke pool routes based on a hub pool address. This can be used later to configure the app more concisely and with less errors
example result from kovan
> feat: add ability to discover all token routes from contracts

- src/data/routes_42_0xD449Af45a032Df413b497A709EeD3E8C112EbcE3.json
Adds a routes json file generated from on chain using a script. Each file is named by the chainId and the hubpool address it was generated by.
> feat: add autogenerated routes file

- src/components/Wallet/Wallet.tsx
- src/data/routes_1_0x6Bb9910c5529Cb3b32c4f0e13E8bC38F903b2534.json
- src/hooks/useBalance.ts
- src/hooks/useBridge.ts
- src/utils/constants.ts
- src/views/Pool.tsx
This adds configuration for mainnet, fixes some bugs that came up with this. To test this view the mainnet deployment (frontend-v2 preview).
Hubpool addresses is based on v1 hubpool, which probably isnt right but currently theres no v2 deployment.
weth address is an env for the pool tab, but i think we could probably update that to deduce from on chain data.
edit: hub pool has been updated with the config store address
> feat: add mainnet routes

- src/components/Header/Header.tsx
Signed-off-by: david <david@umaproject.org>
Makes it so query params stick around between tabs
> fix: allow query params to persist across tabs

- README.md
- package.json
- public/index.html
- src/components/AddressSelection/useAddressSelection.ts
- src/components/ChainSelection/useChainSelection.ts
- src/components/CoinSelection/useCoinSelection.tsx
- src/hooks/useBridge.ts
- src/utils/constants.ts
- src/utils/index.ts
- src/utils/matomo.ts
- src/utils/onboard.ts
- src/views/Send/Send.tsx
- yarn.lock
This copies the functionality from this pr: https://github.com/across-protocol/frontend-v1/pull/179/files.  Adds matomo events, improves v1 slightly by allowing the url to be configured and matomo to be disabled if not provided.
> feat: add matomo events from v1

- src/views/Transactions/TransactionsTable/createTransactionTableJSX.tsx
Story details: https://app.shortcut.com/uma-project/story/5507
> fix: parse decimals on tx history page 

- src/data/routes_1_0x6Bb9910c5529Cb3b32c4f0e13E8bC38F903b2534.json
You can now use the scripts here to generate routes:
https://github.com/across-protocol/helper-scripts. no docs yet but you can run with `yarn routes 1` where 1 represents the chain id of the hubpool you care about
> improve: adds eth/weth routes for mainnet

- src/state/transferHistory.ts
- src/views/Transactions/useTransactionsView.ts
Story details: https://app.shortcut.com/uma-project/story/5510
This PR enables the TX History tab to be updated automatically by fetching events in the background every 10 seconds for 5 minutes max
[Demo video](https://www.loom.com/share/91c998b2236c42a5976fd5dea713f9fa)
> feat: fetch tx history events in background 

- src/components/SendAction/SendAction.tsx
- src/utils/bridge.ts
- src/utils/format.ts
now shows the significant digits
previously
> improve: format numbers to show more sig digits

- src/hooks/useSendForm.tsx
To chain dropdown somtimes grays out routes that shoudl work.
This change resets the toChain selection when fromChain is selected, this resets the total routes that show up, enabling the to chain dropdown.
> fix: reset tochain when fromchain selected

- src/state/connection.ts
- src/utils/onboard.ts
We dont disconnect the wallet if someone locks their wallet. Was not able to reproduce issue in card.
> fix: clear account if wallet locks

- src/state/connection.ts
- src/utils/onboard.ts
I removed this line previously, but i guess it needs to be in there because chain changes do not include account update.
> fix: do not lose existing account on chain change

- src/components/CoinSelection/useCoinSelection.tsx
- src/hooks/useSendForm.tsx
- src/utils/config.ts
Previously form inputs would reset when changing any of the selections.  Now this will not reset the amount, and attempt to keep the token selection and chain selection the same. This does not work in all cases, where its an invalid selection it will try to prioritize resetting the toChain and then the token.
Also the ordering of tokens was fixed, its now set by the constants file token array.
> fix: prevent amount and asset from resetting when switching chains

- src/assets/across-plus-icon.svg
- src/components/Sidebar/Sidebar.styles.tsx
- src/components/Sidebar/useSidebar.ts
- src/views/Transactions/Transactions.styles.tsx
- src/views/Transactions/Transactions.tsx
- src/views/Transactions/TransactionsTable/MobileTransactionsTable.tsx
- src/views/Transactions/TransactionsTable/MobileTransactionsTableWithPagination.tsx
- src/views/Transactions/TransactionsTable/TransactionsTable.styles.tsx
- src/views/Transactions/TransactionsTable/createMobileTransactionTableJSX.tsx
- src/views/Transactions/TransactionsTable/createTransactionTableJSX.tsx
- src/views/Transactions/TransactionsTableModal.tsx
- src/views/Transactions/useTransactionsView.ts
Story Details: https://app.shortcut.com/uma-project/story/5537/add-fill-transfer-transactions-to-transfer-table
Note: also fixes pagination bug ( https://app.shortcut.com/uma-project/story/5568/pagination-breaks-mobile-accordion )
> feat: add Fill TX to TX table

- README.md
- src/hooks/useBalance.ts
- src/hooks/useBlock.ts
- src/utils/constants.ts
- src/utils/query-keys.ts
- src/utils/token.ts
The issue was that a bad balance would flash for a second when switching from chain. 
I dont know exactly what this code did but with it in, it would flash an incorrect balance for a second. With this code the balance goes blank once selecting a new from chain, resolving the issue.
> fix: stop showing bad cache balance values

- src/views/Transactions/TransactionsTable/createTransactionTableJSX.tsx
Signed-off-by: amateima <amatei@umaproject.org>
Partial filled deposits were displayed as 0%. This quick PR fixes the math calculation
> fix: display properly partial fill %

- package.json
- src/components/SendAction/SendAction.tsx
- src/utils/bridge.ts
- src/utils/constants.ts
- yarn.lock
This PR adds two features that come out of updates in the SDK:
1. It updates the way we get Query objects for computing gas costs on each chain (we now use chain-specific objects provided by the SDK).
2. It updates how we compute Network Gas Fees vs Bridge Fees. We group relayer capital costs and LP fees into bridge fees and put _only_ the relayer gas fees into gas fees.
> feat: add new relayer fee logic

- src/utils/constants.ts
> Dropdown on Across v2 for from and to chains should default to "select chain" and the list should be: (1) Ethereum, (2)+ alphabetized.
> improve: sort chains alphabetically

- src/views/Pool.tsx
Update all pools on change instead of the singular one.
> fix: refetch all pool balances on token changes

- src/hooks/useBridge.ts
- src/utils/config.ts
Finding token info by address actually was returning eth, so gas was being subtracted from max preventing it from sending.  the solution is to lookup token by symbol to find out if its native or not.
> fix: max bridge with weth

- src/components/AddressSelection/AddressSelection.styles.ts
- src/components/AddressSelection/AddressSelection.tsx
- src/components/AddressSelection/useAddressSelection.ts
- src/utils/address.ts
- src/utils/constants.ts
Story details: https://app.shortcut.com/uma-project/story/5675/warn-user-that-if-they-re-setting-deposit-recipient-to-a-smart-contract-that-they-will-receive-weth-therefore-tell-them-not
Do getCode(address) call to check if the address inputted is a Contract. If so, show a warning.
To test: Set bridge currency to ETH or WETH, adjust address manually to a known contract address on the toChain, then try to save the address.
> fix: Do a check on overrided address if it's a contract code and show a warning.

- pull_request_template.md
This adds a template for PRs which you can optionally delete if you do not need QA. The idea behind this is that you can request QA and use this template to guide what information is needed about the QA, and how to expect QA testers to respond.
> feat: add qa pr template

- package.json
- src/components/SendAction/SendAction.tsx
- src/components/SendAction/useSendAction.ts
- src/hooks/index.ts
- src/hooks/useBridgeFees.ts
- src/hooks/useBridgeLimits.ts
- src/utils/bridge.ts
- src/utils/query-keys.ts
- src/views/Confirmation/Confirmation.tsx
**Overview**
This change allows us to provide users with a more accurate time estimate for their transfers. Instead of always seeing 1-3 minutes, users should see smaller numbers for smaller transfers and as their transfers get very large, the time estimate should tick up to something intermediate. The amount is different depending on the destination chain.
Instant transfers are estimated to take 1-4 minutes (not 1-3, since a typical bot run takes 2 minutes and a user could deposit on the back end of a run).
Transfers that could be funded by mainnet, but would require an L1->L2 transfer have the following estimates: 
- Optimism: 12-25 minutes.
- Polygon: 20-35 minutes.
- Boba: 12-25 (presuming that it's the same as Optimism).
- Arbitrum: 5-15 minutes.
- Default (not one of the above): …
> feat: add variable bridge time estimation to UI

- src/components/AddressSelection/AddressSelection.styles.ts
- src/components/SendAction/SendAction.styles.ts
Increased the padding below the Send button in order to accommodate  the full height of the menu dropdown
The issue that needs to be fixed:
> fix: fix dropdown menu cut

- src/utils/bridge.ts
- src/utils/constants.ts
- src/utils/format.ts
To make it easier for clients to identify referred transactions, add a delimitter in front of referrer address. By adding in front, this allows referrer-identification logic to be backwards compatible
> feat: Add delimiter to referrer tag

- src/components/PoolForm/RemoveLiquidityForm.tsx
Errors were not being cleared when a valid number was detected in the remove liquidity form input. Now they are.
> fix: fix issue with remove liquidity when decimals are input

- api/limits.js
Currentl Vercel serverless invocations 
Theoretically this # can be reduced by caching responses. Caching the /suggested-fees responses doesn't make sense since the `amount` request parameter will usually be different, but we should be able to cache /limits which does seem like the more requested route.
Idea to cache came from this document which I found by looking up "vercel serverless functions 429"
https://vercel.com/support/articles/what-should-i-do-if-i-receive-a-429-error-on-vercel
> improve(api): Set Cache-Control header to reduce Serverless Invocations

- src/views/Rewards/comp/RewardReferral/RewardReferral.tsx
https://linear.app/uma/issue/ACX-85/link-in-referral-modal-doesnt-work
> fix: add docs url

- api/limits.js
- src/utils/bridge.ts
This limits the max transfer size for WETH at 2500 below the actual LP liquidity and for USDC at 5MM below actual LP liquidity to decrease the likelihood that the LP commits to providing more liquidity than it can intra bundle.
> feat: add LP cushion for WETH and USDC

- src/hooks/useReferralSummary.ts
- src/hooks/useReferrals.ts
- src/utils/query-keys.ts
- src/views/Rewards/Rewards.tsx
- src/views/Rewards/comp/RewardTablePagination/RewardTablePagination.tsx
- src/views/Rewards/comp/RewardTableWithOverlay/RewardTableWithOverlay.tsx
- src/views/Rewards/useRewardsView.ts
This fixes a few issues:
1. There was a hardcoded pagination limit of 30, so users couldn't see more than 30 referrals.
2. The elements per page selector disappeared once a user selected a page size that contained more than their total number of elements. So they couldn't reverse the action. This change allows the user to _always_ select a page size even if they don't need it.
To accomplish this, I had to change the way we query a bit. We lazily load each page of the referrals. In the future, we may _not_ want to do this to reduce the total number of queries, but it seemed like the simplest approach for now.
In the code, this also fixes some issues with the way the hooks were built. We were previously using a constant reactQuery key. This was dangerous because we were using account in the …
> fix: fix pagination issues

- src/views/Transactions/TransactionsTable/createMobileTransactionTableJSX.tsx
- src/views/Transactions/TransactionsTable/createTransactionTableJSX.tsx
parsing token amounts was not using decimal value of token on transfer history page
> fix: decimal parsing of diffent tokens in transfer

- src/utils/format.ts
this pr is updated with a new strategy proposed by korpi:
if number is less than 1, minimum use significant digits
if greater than one use maximum fraction digits
for numbers 1000 or greater, we drop any fractional values
This seems to work well for big and small values
I think with this technique we dont need any tool tips since we both minimize what we show and show necessary decimals when numbers are really small 
new behavior
old behavior
> fix: change formatting style for numbers

- src/hooks/useReferralSummary.ts
This PR fixes the referral summary query key so that it includes the account parameter to avoid cache collisions between accounts.
> fix: fix referral summary query key

- api/_utils.js
- api/pools.js
In order to add Across yield to the [DefiLlama yield server](https://github.com/DefiLlama/yield-server), its convenient if the serverless API exports yield data.
> feat: Add pools route to export APYs

- src/hooks/useBridge.ts
- src/hooks/useReferrer.ts
ref is an allowable queryParam for referrer.
Note: If for some reason both exist I have defaulted to referrer. If anyone has thoughts on this, let me know.
> feature: allow ref to be used; add catch for when both exist.

- README.md
- src/components/Header/Header.styles.tsx
- src/components/Header/Header.tsx
- src/components/Layout/Layout.tsx
- src/hooks/index.ts
- src/hooks/useScrollPosition.ts
- src/views/Rewards/Rewards.styles.tsx
- src/views/Rewards/comp/RewardReferral/RewardReferral.styles.tsx
- src/views/Rewards/comp/RewardReferral/RewardReferral.tsx
- src/views/Rewards/useRewardsView.ts
- src/views/Transactions/Transactions.styles.tsx
Created useScrollPosition hook, when SP > 0 add a border to the navbar
Needs QA
Overview
Acceptance Criteria
How To Report QA
Testers, use the following templates to pass the pull request or to report issues that require a resolution. Following these guidelines will help the developer respond more quickly to issues, but you are free to comment in any way as needed to help resolve issues.
Reporting QA Issues
Testers should use Github comments to report issues with the PR. Use screenshots if relevant, you can also check the [developer console](https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console) to see if there are any logs which might be related. Use the following template when reporting a problem or issue with the PR. You submit multiple comments …
> feat: make navbar sticky

- src/views/Rewards/comp/RewardTableWithOverlay/RewardTableWithOverlay.tsx
Add condition where pagination component only shows when connected, as it's not clickable anyway.
Signed-off-by: Tulun <jaykiraly@gmail.com>
> fix: hide pagination when not connected.

- src/hooks/useReferrals.ts
- src/views/Rewards/comp/RewardTable/createMyReferralsTableJSX.tsx
In the next deployed version of the rewards API, the `realizedLpFeeUsd` field will be replaced by `bridgeFeeUsd`. I added the new field name as fallback when the old field will stop coming from the API. After the new API will be deployed, I'll remove entirely the usage of `realizedLpFeeUsd` response field
> fix: update bridge fee name

- src/views/Rewards/comp/RewardReferral/RewardReferral.tsx
Youtube has strict encoding to create a link on its platform. Adhere to that standard, which should work in other places just fine.
> fix: copy url is more proper link to fix youtube encoding

- api/_utils.js
- api/coingecko.js
- api/limits.js
- api/pools.js
- api/suggested-fees.js
- test/api/main.test.js
Adds route that can cache coingecko pro API responses via Vercel edge caching. We'll be able to call this route internally from /limits and /suggested-fees to reduce coingecko pro API hits
> feat(api): add coingecko route

- .gitignore
- README.md
- cypress.config.ts
- cypress/e2e/bridge.cy.ts
- cypress/e2e/pool.cy.ts
- cypress/e2e/rewards.cy.ts
- cypress/e2e/transactions.cy.ts
- cypress/e2e/wallet.cy.ts
- cypress/support/commands.ts
- cypress/support/e2e.ts
- cypress/support/index.d.ts
- cypress/tsconfig.json
- cypress/utils/ethereum.ts
- package.json
- src/components/ChainSelection/ChainSelection.tsx
- src/components/CoinSelection/CoinSelection.tsx
- src/components/PoolForm/AddLiquidityForm.tsx
- src/components/PoolForm/PoolForm.tsx
- src/components/PoolSelection/PoolSelection.tsx
- src/components/SendAction/SendAction.tsx
- src/components/Wallet/Wallet.tsx
- src/utils/onboard.ts
- src/views/Rewards/comp/RewardReferral/RewardReferral.tsx
- src/views/Rewards/comp/RewardTable/RewardTable.tsx
- src/views/Transactions/Transactions.tsx
- yarn.lock
This adds rudimentary integration tests and the required cypress setup. The test scenarios are still very minimal and use a mocked web3 provider for now. The scope was to make sure that
- each route renders
- basic UI interactions work
We can add more/refine tests as we see fit in the future.
Integration with GitHub Actions will follow in a separate PR.
> test(integration): rudimentary cypress tests

- .github/actions/setup/action.yaml
- .github/workflows/lint-test.yaml
- package.json
- yarn.lock
This PR adds initial GitHub Action workflows for linting and running cypress tests. Someone who is an admin of this repository needs to add the following secrets before the run succeeds:
- `CYPRESS_PUBLIC_INFURA_ID`
- `CYPRESS_PUBLIC_ONBOARD_API_KEY`
- `CYPRESS_REWARDS_API_URL`
- `CYPRESS_CHAIN_137_PROVIDER_URL`
- `CYPRESS_CHAIN_42161_PROVIDER_URL`
You can have a look at my forked repository where I tested this https://github.com/dohaki/across-frontend-v2/pull/1 to see a successful run.
> ci: initial lint + cypress test run github actions

- src/utils/bridge.ts
Because bundles are usually delayed from proposing immediately after a previous one, we should extend the time that we estimate for slow relays.
> Make slow relay delay longer due to bundle block delays

- api/coingecko.js
Our goal is to reduce cache misses as they result in very slow response times for callers because of the lambda function instantiation
> improve(coingecko): Increase cache duration to 5 mins

- package.json
- yarn.lock
Desired feature from this sdk version is an improved coingecko client that reduces the amount of requests sent to the Pro API: https://github.com/across-protocol/sdk-v2/commit/ca0de27d29e84b4a6ea42bb4a325ada2c0c63121
> chore: bump sdk-v2 to 0.1.19

- api/_utils.js
- src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json
This fixes a bug in the routes computation where some of the added addresses were not in the checksum format.
Changes:
- Updates those addresses to the correct checksum format.
- Changes the failing comparison to use .toLowerCase before comparing to ensure that non-checksummed addresses would work (i.e. this will prevent this sort of thing in the future).
In general, we should _always_ use checksummed addresses, but a resilient comparison function will mean that mistakes in the input format will not cause bugs like this.
> fix: fix checksum address issue in routes computation

- src/hooks/useReferralSummary.ts
- src/state/hooks.ts
1. Displays a checksum address instead of the address, which is returned by Onboard V2.
> fix: convert address to checksum

- .env.example
- src/Routes.tsx
- src/utils/constants.ts
Proposed solution for:  https://linear.app/uma/issue/ACX-260/prepare-banner-warning-users-that-bridge-will-be-offline-before-and
Make a generalized configurable message that can be changed in Vercel. We can't do formatting much this way but it might be useful to have something we can do without a PR in Vercel at a moment's notice.
To test, you should start this branch locally and add to your local .env, as I don't want to add this to environment variables until we are ready.
> feat: Add general maintenance banner.

- src/views/Transactions/utils.ts
The all transactions view PR https://github.com/across-protocol/frontend-v2/pull/221 didn't have merge conflicts but was based on an older across-sdk version with incompatible types. This fixes it.
> build: fix by adapting to new sdk version

- src/components/PoolForm/RemoveLiquidityForm.tsx
Motivation
UI was crashing when inputting very small numbers to withdraw from pool
Solution
We have to call tofixed on the decimal when passing into the preview. unfortunately for now the sdk specifies this is passed as a decimal, and probably should be sanitizing in there, but this will acheive the same effect easier by making the change on the FE
> fix: pool removal crashing with small amounts

- .env.example
- src/components/SendAction/SendAction.tsx
- src/utils/bridge.ts
- src/utils/config.ts
- src/views/Confirmation/Confirmation.tsx
1. Built utility functions to help with time range calculation.
2. Tested via REACT_APP_DEPOSIT_DELAY= { "1": 2, "10": 2, "137": 2, "288": 2, "42161": 2 }
QA: Each of the different `toChain` paths for a given `fromChain` should show the current time estimates + 2 mins
> feat: additional delay calc logic configurable by REACT_APP_DEPOSIT_DELAY

- src/hooks/index.ts
- src/hooks/useNotify.ts
- src/hooks/useOnboard.tsx
- src/state/hooks.ts
- src/utils/constants.ts
- src/utils/format.ts
- src/views/Transactions/MyTransactions.tsx
- src/views/Transactions/Transactions.styles.tsx
- src/views/Transactions/components/SpeedUpModal/InputWithButton.tsx
- src/views/Transactions/components/SpeedUpModal/SpeedUpModal.styles.tsx
- src/views/Transactions/components/SpeedUpModal/SpeedUpModal.tsx
- src/views/Transactions/components/SpeedUpModal/SpeedUpStats.tsx
- src/views/Transactions/components/SpeedUpModal/index.tsx
- src/views/Transactions/components/SpeedUpModal/utils.tsx
- src/views/Transactions/components/TransactionsTable/TransactionsTable.styles.tsx
- src/views/Transactions/components/TransactionsTable/TransactionsTable.tsx
- src/views/Transactions/components/TransactionsTable/rows/DataRow.tsx
- src/views/Transactions/components/TransactionsTable/rows/HeadRow.tsx
- src/views/Transactions/components/TransactionsTable/rows/MobileDataRow.tsx
- src/views/Transactions/hooks/useSpeedUp.tsx
- src/views/Transactions/hooks/useTxClient.ts
- yarn.lock
This adds a first-pass version of the speed up modal. There is one optional TODO/blocker but this can be adjusted in an upcoming PR.
Testing this feature is a bit tricky. I tested it by setting a very low relayer in the `useBridge.ts` hook locally, e.g.
```
relayerFeePct: ethers.utils.parseEther("0.0001"), // 0.01%
```
**TODOs:**
Videos of user flow
https://user-images.githubusercontent.com/17645687/190171829-df8abbe4-24da-4977-aac6-9a8d671bcb77.mov
> feat: speed up modal

- src/views/Transactions/components/SpeedUpModal/InputWithButton.tsx
- src/views/Transactions/components/SpeedUpModal/SpeedUpModal.tsx
Remove `MAX` button in speed up modal for now, until better-suited function is found.
> fix: remove max relayer fee button

- api/_utils.ts
Vercel logging can be expensive and we're not in control of when clients trigger the API that log. We should be able to turn off non-critical logs with a boolean flip easily
> feat(api): Exit early from debug level logs if boolean is switched on

- src/components/Sidebar/useSidebar.ts
- src/hooks/useScrollPosition.ts
On some devices and also on the preview links, the opacity change animation was a bit laggy. Not sure if that only happens on my machine 🤔  I added a throttle with a wait of 50ms so that it still feels smooth but drastically reduces the number of state updates. Also added the `/airdrop` link to the sidebar.
> perf: throttle scroll handler

- src/views/PreLaunchAirdrop/components/CardContent.tsx
- src/views/PreLaunchAirdrop/components/CardIcon.tsx
The LP icon size was a bit off. I adjusted the wrapper to enforce a fixed size. Also removed the text-decoration from the "Go to Pools" button.
Previous
Now
> fix: lp icon size

- src/utils/query-keys.ts
- src/views/PreLaunchAirdrop/api/useGetPrelaunchRewards.ts
The community eligibility data didn't update instantly after a successful Discord authentication. To solve this we make the query key dependent on the JWT.
> fix: refetch rewards on successful discord auth

- .github/workflows/lint-test.yaml
- cypress/e2e/prelaunch.cy.ts
- src/components/GlobalStyles/GlobalStyles.tsx
- src/views/PreLaunchAirdrop/components/AirdropCard.tsx
- src/views/PreLaunchAirdrop/components/MoreInfoFlow/MoreInfoFlow.tsx
- src/views/PreLaunchAirdrop/components/TitleSection.tsx
- src/views/PreLaunchAirdrop/components/cards/BridgeTravelerCard.tsx
- src/views/PreLaunchAirdrop/components/cards/BridgeUserCard.tsx
- src/views/PreLaunchAirdrop/components/cards/CommunityRewardCard.tsx
- src/views/PreLaunchAirdrop/components/cards/LiquidityProviderCard.tsx
This adds some basic /airdrop route e2e tests. For the more refined ones (connected wallets with different eligibility states), I don't know yet which approach we should take, i.e. I will open separate PRs.
> test: add basic set of airdrop e2e tests

- src/components/Layout/Layout.tsx
While fixing the stickyness of the header when scrolling, the old layout component wasn't updated.
> fix: old layout min height

- api/_utils.ts
This adds a way to specify an override URL for a particular network in the API.
This is done by adding `OVERRIDE_PROVIDER_[chainId] = https://...` as an env.
> feat: add a way to specify an override provider for the API

- src/utils/bridge.ts
- src/utils/constants.ts
This PR removes the `relayerFeeCapitalCostConfig` object from the Across FE.
> fix: remove depreceated fee file

- api/_constants.ts
- api/suggested-fees.ts
This should be combined with a change to the relayer code [here](https://github.com/across-protocol/relayer-v2/pull/340) that will make relayer ignore any quote times that do not sufficiently lag HEAD
> improve(api): Add quote timestamp buffer to suggested-fees route

- src/data/routes_5_0xA44A832B994f796452e4FaF191a041F791AD8A0A.json
- src/hooks/index.ts
- src/hooks/useIsWrongNetwork.ts
- src/utils/config.ts
- src/views/Staking/Staking.tsx
- src/views/Staking/components/StakingForm/StakingForm.tsx
- src/views/Staking/hooks/useStakingAction.ts
- src/views/Staking/hooks/useStakingPool.ts
- src/views/Staking/hooks/useStakingView.ts
- src/views/Staking/types.ts
This PR splits the existing `src/views/Staking/hooks/useStakingActionsResolver.ts` hook into composable hooks and allows the reusage of them on `/rewards/staking/{pool}` page, as well as on `/rewards` page.
I also refactored them to be based on `react-query`, so loading/fetching states are handled automatically. 
~I left this as a draft until @james-a-morris gave me some guidance on how to test this properly. Afterward, I will also remove the refactored monolithic `useStakingActionsResolver` hook.~ Tested locally.
> feat: split up staking pool hooks

- package.json
- yarn.lock
This pr removes eth-optimism package as it seems that there is no need in it. Is it duplicated in @across-protocol package
This change will increase speed of app downloading as it is resulted in 35% decreasing of vendors chunk:
`2.5Mb (gzipped) => 1.6Mb (gzipped)`
> chore: Remove eth-optimism package

- src/views/Referrals/comp/RewardReferral/RewardReferral.tsx
The referrals page was broken for tier 5 referrals.
> fix: referral page broke for tier 5 referrals

- api/limits.ts
The limits API endpoint assumes that the L1 (bridged) token is priced in the native gas token. getCachedTokenPrice() defaults to returning prices in ETH terms when baseCurrency is not specified.
When pricing the bridged token in ETH terms on Polygon, it incorrectly devalues the bridged token and therefore produces an artificially high minimum deposit amount.
Issue initially reported by the curious minds over at Rango Exchange.
> fix(limits): Fix minDeposit derivation on Polygon

- api/limits.ts
Per the existing implementation, for DAI, UMA, BAL (and future ACX) , we've called getAddress()
4 times on the same token address.
The new code unfortunately got a bit squashed by the formatter...it'd be a lot more concise if
the lpCushions object declaration/assignment could be handled on one line per key/value.
> improve(limits): Reduce unnecessary getAddress() calls

- api/limits.ts
- src/utils/bridge.ts
- src/utils/constants.ts
This adds code to allow LP cushions for BAL, UMA, and BOBA similar to the ones we already have for WETH, DAI, USDC, and WBTC.
> feat: add BAL, UMA, and BOBA cushions

- api/_utils.ts
https://linear.app/uma/issue/ACX-461/limits-with-destinationchainid=288-fails
Fixes bug introduced in https://github.com/across-protocol/frontend-v2/commit/742f3e54f8f7a5d0ef1c0d59d100c345ff274303#diff-428e8c9eb80e1971d1eb1d20244ebe4791f3f5d6c6c664cb694759f503874251
> fix: Return correct boba provider in getProvider

- api/pools.ts
- package.json
- yarn.lock
No longer need to fix estimatedApr and estimatedApy from /pools route to 18 decimals
> improve: Upgrade sdk-v2 to 0.1.34

- src/components/Footer/Footer.tsx
- src/components/Layout/Layout.tsx
Footer links for routes `/pool` and `/bridge` could not be clicked.
> fix: footer links old layout

- src/views/Staking/components/StakingForm/StakingForm.tsx
Our custom `formatUnits` also shortens and rounds the decimals and therefore loses precision. We fix this by using the `formatUnits` of ethers for setting the max values during staking/unstaking.
In the future, it could make sense to rename our custom formatter to smth like `formatUnitsMaxDecimals` or similar so that it is clear that this utility also rounds decimals.
> fix: stake/unstake max button value

- api/limits.ts
A follow-up commit needs to map symbol, address and decimals, so it makes sense to factor it out.
> improve(limits): Dynamically source LP cushion

- api/limits.ts
Requested by a partner, this will allow a lower bound for the minimum
deposit to be specified in the environment via the
REACT_APP_MIN_DEPOSIT_USD env var. This env var is specified as a JSON
object, mapping chain ID to the floor amount in USD.
An initial proposed REACT_APP_MIN_DEPOSIT_USD config would be:
`'{ "1": 10, "10": 5, "137": 2, "288": 5, "42161": 5 }'`
> feat(limits): Support minimum deposit floor

- src/components/PoolForm/PoolForm.tsx
This change aims to resolve the double accounting for staking positions on both the FE & the SDK. 
Initial Bug Report:
> fix: :ambulance: remove duplicate funds from pool position that are staked

- src/components/PoolForm/PoolForm.tsx
This change utilizes the specific number of decimals that are available to a LP token position. The previous change used formatEther which defaulted to 18 decimals of precision.
> fix: :ambulance: resolve pool UI formatting

- api/suggested-fees.ts
- package.json
- src/utils/bridge.ts
- yarn.lock
LP fees should distinguish rate models for certain deposit paths
Let's not merge this until we add the `routeRateModel` on-chain in the ConfigStore. I'll run some `e2e` tests from the `sdk-v2` to make sure that the FE will be able to read these new rate models
> feat: Account for route-specific rate models

- yarn.lock
Removes some deps from lock file that might got lost during rebase
> chore: remove remaining redux from lock

- src/views/LiquidityPool/components/ActionInputBlock.tsx
- src/views/LiquidityPool/hooks/useLiquidityAction.ts
Remove liquidity didn't work for max. values because we passed in the L1 token amount instead of the converted LP token amount.
> fix: correct remove liquidity amount

- src/hooks/useApprove.ts
- src/utils/notify.ts
- src/views/Airdrop/hooks/useClaimAndStake.tsx
- src/views/Bridge/hooks/useBridgeAction.ts
- src/views/LiquidityPool/hooks/useLiquidityAction.ts
- src/views/Referrals/hooks/useClaimReferralRewards.tsx
- src/views/Staking/hooks/useClaimStakeRewardAction.ts
- src/views/Staking/hooks/useStakingAction.ts
For some reason, `txResponse.chainId` returns always `0`. So the `waitOnTransaction` helper falls back to `tx.wait` event for supported chains.
> fix: explicitly pass required chain to waitOnTx helper

- src/components/RouteTrace/useRouteTrace.ts
- src/hooks/useReferrer.ts
The `PageViewed` event property `referralProgramAddress` wasn't correctly tracked for the initial page.
> fix(ampli): ensure resolved referralProgramAddress before page view tracking

- src/hooks/useIsWrongNetwork.ts
- src/views/Bridge/Bridge.tsx
- src/views/Bridge/components/BridgeForm.tsx
- src/views/Bridge/hooks/useBridge.ts
- src/views/Bridge/hooks/useBridgeAction.ts
- src/views/LiquidityPool/LiquidityPool.tsx
- src/views/LiquidityPool/components/ActionInputBlock.tsx
This adds a new button at the same place as the main action of the pool or bridge page to switch networks. Similar to the old designs.
The PR also contains smaller fixes:
- Local handling of pending deposits (was accidentally removed while refactoring)
- Input reset and loading indicator fix
> refactor: bridge enforce network

- api/_utils.ts
On GCP the error property was an empty object, i.e. `{}`. The reason is that `JSON.stringify(new Error())` returns `{}`.
> fix: error log on gcp

- src/views/LiquidityPool/components/ActionInputBlock.tsx
- src/views/LiquidityPool/hooks/useLiquidityAction.ts
- src/views/LiquidityPool/hooks/useMaxAmounts.ts
Instead of converting the max. removable amount to LP when calling `removeLiquidity`, we instead calculate the ratio of `amountInput / maxRemovableAmount (both denominated in tokens)` and take that percentage from the `maxRemovableAmountLP`. This should mitigate the risk of stale exchange rate values that prevented the user from previously executing the action.
Fixes ACX-694
> fix: make max. removable amount more robust to volatile exchange rates

- src/views/LiquidityPool/components/ActionInputBlock.tsx
The action button for adding/removing liquidity wasn't correctly disable if amount input was empty.
> fix: disable lp action if no amount or data

- src/components/Selector/Selector.tsx
- src/views/Bridge/Bridge.tsx
- src/views/Bridge/components/BridgeForm.tsx
- src/views/Bridge/components/CoinSelector.tsx
- src/views/Bridge/hooks/useBridge.ts
This PR allows all chains/assets to be visible to the user when a user clicks a dropdown. However, the selectors now `disable` inconsistent/unavailable route combinations.
> feat: include greyed-out selectors for all routes/tokens

- src/hooks/useConnection.ts
Sentry uncovered a bug that occurred for accounts with ENS
> fix: ens name display

- src/views/Rewards/components/GenericStakingPoolTable/GenericStakingPoolFormatter.tsx
- src/views/Staking/components/StakingForm/StakingForm.tsx
This change introduces the following change: 
- On the rewards page, pools table(s) on APY column
- In the tool tip, update to "…including the pool APY plus rewards APR times…"
- On the staking page
- Update label to "Rewards APR"
- In the APY tooltip, update to "…plus rewards APR…"
- In the rewards apy tooltip, update to "…base reward APR times…"
> improve: change copy on reward/staking page

- api/_constants.ts
- api/_utils.ts
- api/limits.ts
- api/suggested-fees.ts
- package.json
- src/utils/bridge.ts
- yarn.lock
This test enables a capital fee override for USDC between its Optimism <> Arbitrum route.
> test: enable per-route capital fee config

- src/utils/math.ts
Currently, the `fees.relayerGasFee` is included in the calculation of the true bridge fee. However, this approach doesn't accurately represent the actual fee charged to users. 
After removing the inclusion of `fees.relayerGasFee` from the calculation of the true bridge fee, users will have a more accurate representation of the actual fee charged. This will improve transparency and provide a better user experience.
> fix: :ambulance: remove gas fee from bridge fees

- src/App.tsx
- src/components/WalletBalanceTrace/useWalletBalanceTrace.ts
During regular FE execution, the `AllAssetsAllNetworksWalletCurrentBalanceUsd` user property was not being correctly set. This error was caused by commit [`3c21999`](https://github.com/across-protocol/frontend-v2/commit/3c2199935fed0ea9f2d13d61a3aef0c7b21ca9fe), which removed the environment attribute for amplitude, leading to the incorrect setting of the user property.
Additionally, this PR also contains logic to retry the `AllAssetsAllNetworksWalletCurrentBalanceUsd` instrumentation every 30 seconds during a user's session until uploaded.
> improve: properly set AllAssetsAllNetworksWalletCurrentBalanceUsd

- api/_utils.ts
- api/limits.ts
This change includes a critical hotfix to correct the `/api/limits` endpoint to use the proper gas destination fee source.
> fix(ui): 🚑 correct api origin / destination fee details

- src/hooks/useOnboard.tsx
This change corrects for the auto-connect functionality that was occasionally breaking the FE. This change adds a new option to the `customOnboardConnect` function to enable the autoconnect functionality. This is a correction from the previous logic because in production, currently the autoconnect tries to keep silentely failing causing some users to not be able to connect.
> fix(ui): :ambulance: resolve autoconnect issue

- api/_constants.ts
- api/suggested-fees.ts
This should allow relayers to hit the cache more often when computing realized LP fees
1 minute of error in quote time also seems like it would have zero impact on realized LP fees charged to deposits
UPDATE: We may want to decrease the precision and use something like every 5 minutes, every 2 minutes
> improve(api): Set quoteTimestamps equal to nearest minute

- src/hooks/useApprove.ts
- src/hooks/useStakingPool.ts
- src/hooks/useWalletTokenImport.ts
- src/utils/config.ts
- src/utils/pool.ts
- src/utils/tokenRoutes.ts
- src/utils/typechain.ts
- src/views/Staking/hooks/useStakingAction.ts
While updating to `@across-protocol/contracts-v2@2.1.0-beta.1`, I had to circumvent some issues with the latest `@uma/common` package, which currently is not really compatible with a browser environment. The workaround is to import the typechain bindings via an explicit path. 
Then I noticed that our bundle size got smaller. It seems that the packages `@across-protocol/contracts-v2` and `@across-protocol/across-token` can not be tree-shaken if we import stuff directly from the main entry file. Until we fix this upstream, I decided to add a wrapper module `utils/typechain.ts` that re-exports the respective bindings. This results in a **300 kB (gzipped)** decrease in the bundle size.
> perf: improve tree-shaking typechain

- src/utils/constants.ts
The transactions page was crashing if the history contains deposits from/to BOBA, which was removed. Instead of filtering out the deposits, I decided to remove the assert from the helper. 
Example issue on Sentry https://risk-labs-m6.sentry.io/issues/4053538768/events/5e0353ebbcd44910ba0744423db4ea4f/
> fix: app crash on transactions page

- api/_utils.ts
- api/available-routes.ts
- api/limits.ts
- api/suggested-fees.ts
- package.json
- src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json
- src/data/routes_5_0x0e2817C49698cc0874204AeDf7c72Be2Bb7fCD5d.json
- src/hooks/useDeposits.ts
- src/utils/bridge.ts
- src/utils/constants.ts
- src/utils/deposits.ts
- src/utils/index.ts
- src/utils/providers.ts
- src/utils/utils.d.ts
- src/views/Bridge/components/BridgeForm.tsx
- src/views/Bridge/components/DepositConfirmation.tsx
- src/views/Bridge/hooks/useBridgeAction.ts
- src/views/Transactions/components/SpeedUpModal/SpeedUpModal.tsx
- src/views/Transactions/hooks/useSpeedUp.tsx
- yarn.lock
Closes ACX-643, ACX-1029 and ACX-898.
This PR updates the frontend to be able to handle the new v2.5 contracts. Note, that the base is set to #704 because this PR needs the adjusted serverless API to work on Goerli.
Additional note, the preview links will only work on Goerli. Mainnet previews might be broken until we deploy and update the respective v2.5 contracts.
> feat: v2.5 adjustments for deposits + speed ups

- src/views/Bridge/hooks/useBridge.ts
Similar to #707 but related to the fees query. Example issue on Sentry https://risk-labs-m6.sentry.io/issues/3938438386/events/bbf1a146109f4ea1ac878ffdfa36f24c/
> fix: fee query 400 code due to same origin + dest

- src/hooks/useAmpliTracking.ts
- src/hooks/useAmplitude.tsx
- src/hooks/useInitialUserPropTraces.ts
- src/hooks/useOnboard.tsx
- src/hooks/useRouteTrace.ts
- src/hooks/useWalletBalanceTrace.ts
- src/hooks/useWalletTrace.ts
- src/views/Bridge/components/ChangeAccountModal.tsx
- src/views/Bridge/components/CoinSelector.tsx
- src/views/Bridge/components/SlippageAlert.tsx
- src/views/Bridge/hooks/useBridge.ts
- src/views/Bridge/hooks/useBridgeAction.ts
- src/views/LiquidityPool/components/ActionInputBlock.tsx
- src/views/Staking/components/StakingInputBlock/StakingInputBlock.tsx
Fixes ACX-1044
The initial user props were not reset when the user connected a wallet by clicking the `Connect wallet` button or changed the account in the wallet directly.
This PR fixes the issue by re-running the `src/hooks/useInitialUserPropTraces.ts` hook if the connected account changes. We also make sure to wrap every tracking call with the `addToAmpliQueue` function, to avoid missing updated user properties.
> fix(ampli): reset user props on account change

- src/views/Bridge/components/BridgeForm.tsx
- src/views/Bridge/components/CoinSelector.tsx
This change modifies the error readouts to produce the correct alert to the user depending on the number of funds they request to bridge.
> fix: :bug: correct error readout in bridge tab

- public/index.html
Leaving this here is a security risk because it could allow users who previously had access to regain access.
> fix: remove old google site verification

- .env.example
- api/_utils.ts
- api/available-routes.ts
I decided to add a separate env var for disabling tokens in the API because for testing purposes it was handy to have new tokens enabled in the API but disabled in the UI.
> feat(vercel): add env var to disable tokens in API

- src/components/Tooltip/Tooltip.tsx
- src/hooks/useConnection.ts
- src/hooks/useIsContractAddress.ts
- src/views/Bridge/Bridge.tsx
- src/views/Bridge/components/BridgeForm.tsx
- src/views/Bridge/components/ChangeAccountModal.tsx
- src/views/Bridge/components/EstimatedTable.tsx
- src/views/Bridge/components/TokenFee.tsx
- src/views/Bridge/hooks/useBridge.ts
- src/views/Bridge/hooks/useToAccount.ts
- src/views/Referrals/comp/StepperWithTooltips/useStepperWithTooltips.tsx
Closes ACX-1119
Displays info tooltip and correct receiving token symbol (WETH) when the user attempts to bridge ETH from Mainnet to Polygon. The same tooltip is also displayed if the receiving address is a contract deployed on the destination chain.
This PR also includes a fix for a bug where a user could not reset/clear a custom changed `toAddress`.
> feat: display weth info when bridging eth mainnet -> polygon or contract

- api/_utils.ts
- api/build-deposit-tx.ts
- api/suggested-fees.ts
- api/token-list.ts
This PR adds some helper endpoints in an effort to be included in the DODO aggregator:
- `GET /api/build-deposit-tx`
- Populates a raw deposit tx that can be signed. See https://github.com/DODOEX/dodo-bridge-aggregator#iv-buildtransactiondata
- `GET /api/token-list`
- Returns a list of enabled tokens per enabled chain. See https://github.com/DODOEX/dodo-bridge-aggregator#iii-tokenlist
> feat: required api endpoints for dodo

- src/views/Bridge/Bridge.tsx
- src/views/Bridge/components/BridgeForm.tsx
- src/views/Bridge/components/DepositConfirmation.tsx
- src/views/Bridge/components/EstimatedTable.tsx
- src/views/Bridge/utils.ts
Fixes ACX-1119
This refines the tooltip and warning based on the behavior for ETH/WETH:
- If a bridge transfer is being sent to an EOA, the EOA will receive ETH (not WETH)
- If a bridge transfer is being sent to a contract or to Polygon, the contract will receive WETH (not ETH)
> fix: weth/eth tooltip and warning

- src/views/Transactions/hooks/useSpeedUp.tsx
Fixes ACX-1219
This is only a partial fix. I have another PR https://github.com/across-protocol/scraper-api/pull/241 open for the Scraper that should fully fix the speed up.
> fix: use default message for speed up

- vercel.json
Walletconnect V2 uses different domains which we need to whitelist to suppress some noisy errors
> fix: CSP for walletconnect v2

- src/views/Bridge/components/CoinSelector.tsx
Improve tooltip text if bridge token is not supported on route.
> improve: asset not supported tooltip

- api/_constants.ts
- api/_utils.ts
- api/pools.ts
- package.json
- src/utils/serverless-api/mocked/index.ts
- src/utils/serverless-api/mocked/pools.mocked.ts
- src/utils/serverless-api/prod/index.ts
- src/utils/serverless-api/prod/pools.ts
- src/utils/serverless-api/types.ts
- yarn.lock
Extends `/pools` API to allow
```
GET /pools?token=0x&externalPoolProvider=balancer
```
Adds support for external Balancer pool. The staking page will eventually call this endpoint on the frontend to determine the pool APY.
Part of ACX-1351
> feat(api): extend `/pools` to handle balancer pool tokens

- src/hooks/useStakingPool.ts
- src/views/LiquidityPool/components/EarnByStakingInfoBox.tsx
I removed an unused property in #797 but tested this only with #798. This extracts the change until #798 is merged.
> fix: remove unused share of pool

- api/_utils.ts
- api/limits.ts
- api/suggested-fees.ts
- src/utils/constants.ts
- src/utils/providers.ts
This allows the usage of the env var `REACT_APP_CHAIN_<CHAIN_ID>_PROVIDER_URL` to override the default Infura provider URL. 
Setting the above env var will affect all RPC calls for the respective chain in all API handlers and on the frontend. Previously, we had the env var `OVERRIDE_PROVIDER_<CHAIN_ID>` which will be replaced by the shared one on the frontend.
> feat: allow usage of override infura provider urls everywhere

- src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json
Available routes currently contains a duplicate set of available routes from ZKSync to Optimism. This PR removes that.
> chore: remove duplicate available routes

- src/components/Text/Text.tsx
This change adds the ability for the `<Text />` primitive component to be passed, as input, a casing modifier. In doing so, we can directly handle directives such as `uppercase`, `lowercase`, and `capital case`.
> feat: add casing to `<Text />` primitive

- src/views/Splash/hooks/useSplash.ts
If the `Fast` tab in the splash screen has an average of one minute, use `minute` instead of `minutes`.
> improve: dynamic spelling

- api/_utils.ts
Per a meeting today with leadership, we should be using `swap fees` + `tokenAprs` to compute the pool APY.
> fix: use correct pool APY

- src/views/Bridge/hooks/useAmountInput.ts
- src/views/Bridge/utils.ts
This PR changes the behavior of clearing the bridge amount input only if the newly selected token is truly different.
> fix: do not clear amount input for interchangeable tokens

- api/_utils.ts
- src/views/Transactions/components/TransactionsTable/cells/StatusCell.tsx
Per the new TSDX removal PR (https://github.com/across-protocol/sdk-v2/pull/382), we should remove references to the `dist` directory where possible.
> improve: change sdk imports & refactor imports

- package.json
- yarn.lock
This bumps cypress to the latest version. This should also fix our CI. Related https://github.com/cypress-io/cypress/issues/27804
> chore: bump cypress to latest

- src/views/Bridge/components/AmountInput.tsx
- src/views/Bridge/hooks/useTransferQuote.ts
Fixes ACX-1550
The problem was that we validated the input only when the user focussed and blurred the input. This PR changes the logic so that we validate when the user enters something.
> fix: validate on entered amount not on blur

- src/views/Bridge/hooks/useBridge.ts
- src/views/Bridge/hooks/useBridgeAction.ts
Hopefully fixes ACX-1565
I could reproduce the above issue when I rejected the transaction within MetaMask and afterward changed the route or amount.
The root causes were:
- Fees were not updating when the action mutation errored by user rejecting a tx
- We did not let these kinds of errors bubble up and suppressed them.
> fix: update quote on error

- api/_constants.ts
- api/_utils.ts
- api/coingecko.ts
- api/token-list.ts
- package.json
- src/utils/constants.ts
- src/views/Bridge/components/RouteNotSupportedTooltipText.tsx
- yarn.lock
This brings this repo in sync with sdk-v2, relayer-v2, contracts-v2 so that all constants are imported from a single place rather than having to ripple all changes from contracts-v2 --> sdk-v2 --> *
Signed-off-by: nicholaspai <npai.nyc@gmail.com>
> feat: Import CHAIN_IDs and TOKEN_SYMBOLS_MAP from constants-v2 instead of sdk-v2

- src/views/Bridge/hooks/useBridgeAction.ts
- src/views/Bridge/hooks/useTransferQuote.ts
In some edge cases the quote time wasn't set properly which led to a disabled bridge action button.
> fix(bridge): initial quote time issue

- src/utils/amplitude.ts
The `quoteTimestamp` event property should be in seconds and not in milliseconds.
> fix(ampli): quoteTimestamp precision

- api/_constants.ts
This PR updates the capital fee computation to the Across Parameters doc. These changes affect the `UB`, `LB`, and `Cutoff` for `WETH`, `ETH`, `UDSC`, `USDT`, and `DAI`.
> improve: align rate model with correct parameters

- src/utils/transactions.ts
The PR https://github.com/across-protocol/frontend-v2/pull/849 caused an issue with on-chain actions that were wrapped by `sendWithPaddedGas` because we didn't spread the args properly.
> fix: spread args in send with padded gas utils

- src/components/ErrorBoundary/ErrorBoundary.tsx
- src/hooks/useWalletTrace.ts
Fixes ACX-1532
When changing the account in the MetaMask mobile browser, the `wallet.accounts` array is empty for a short period of time. This led to a fatal crash of the app.
> fix: MetaMask browser app crash on wallet change

- src/utils/constants.ts
- src/views/Bridge/hooks/useMaxBalance.ts
This PR makes setting the max. bridgable amount for native token deposits more ~accurate and~ reliable by:
- Removing the usage of a fallback value gas costs and using infinite retry
- Using a pre-computed value for gas expenditure instead of querying via an additional RPC call
> fix: use pre-computed gas usage for deposit max amounts

- api/_utils.ts
- package.json
- src/utils/constants.ts
- yarn.lock
We shouldn't be allowed to set a backup default cost config fee. This is indicative of a misconfured capital cost setting. We should have an intentional default for a given token or else we should fail.
A failure condition has been added to https://github.com/across-protocol/sdk-v2/pull/430 and we will need to bump the SDK before we merge this change.
> fix: :bug: remove ability to specify backup capital cost fee

- src/ampli/index.ts
- src/utils/bridge.ts
- src/views/Bridge/hooks/useBridgeAction.ts
> feat: track deposit network mismatch

- api/limits.ts
We should use the token details to get the decimals so that we're passing one token of value to simulate the relayer details.
> fix: use specific 1 token value

- api/_utils.ts
- api/suggested-fees.ts
- src/hooks/useBridgeFees.ts
- src/utils/bridge.ts
- src/utils/serverless-api/mocked/suggested-fees.mocked.ts
- src/utils/serverless-api/prod/suggested-fees.prod.ts
- src/utils/serverless-api/types.ts
- src/views/Bridge/hooks/useTransferQuote.ts
- src/views/Transactions/hooks/useSpeedUp.tsx
We discovered a short circuit in the Vercel API's estimation of fee quotes. 
This was causing a quote of roughly 80K gas units to make a fill. 
The original recipient address being used on the FE is `0xBb23Cd0210F878Ea4CcA50e9dC307fb0Ed65Cf6B`, which will incur a storage cost during the initial ERC20 transfer of 145,000 gas units. Properly passing `recipientAddress` in the suggested-fees endpoint on prod will incur 120,000 gas units.
In either case, we now default our recipient address to incur the storage cost of the ERC20 initializing a user's balance in the token.
Thus, the cost calculation will be preserved regardless of `recipientAddress` being provided and using the Across UI will produce a more accurate gas estimation making it the cheaper alternative over aggregators. 
Closes: …
> improve: more effectively estimate suggested fees quote

- api/suggested-fees.ts
To reduce misalignment between the SpokePool deposit() input parameters and the parameter names supplied to /suggested-fees, rename the following:
recipientAddress -> recipient
relayerAddress -> relayer
This leaves only `token` as the variable name that differs.
> refactor: Align /suggested-fees inputs w/ SpokePool names

- src/hooks/useBridgeFees.ts
- src/utils/bridge.ts
- src/utils/serverless-api/mocked/coingecko.mocked.ts
- src/utils/serverless-api/mocked/suggested-fees.mocked.ts
- src/utils/serverless-api/prod/suggested-fees.prod.ts
- src/utils/serverless-api/types.ts
We no longer require `/suggested-fees` have a `recipient` as input. Additionally, we're passing `recipientAddress` instead of `recipient` per https://github.com/across-protocol/frontend-v2/commit/85c862142067491527493f3045180f335fcf1253.
Let's update the UI to reflect these name changes and required statuses.
> improve: relax suggested-fees params

- src/components/InputWithMaxButton/InputWithMaxButton.styles.tsx
- src/views/Bridge/components/AmountInput.tsx
- src/views/Staking/components/StakingInputBlock/StakingInputBlock.styles.tsx
Fixes some regression bug on mobile
> fix: max button responsiveness

- src/views/Transactions/hooks/useSpeedUp.tsx
> fix: throw speed up mutation if depositor does not match signer

- src/views/Bridge/hooks/useBridge.ts
- src/views/Bridge/hooks/useTransferQuote.ts
If a user connects a wallet via the primary CTA button on the bridge page, it leads to the quote not being updated. Ideally, the call to `connect()` should be in a separate handler/mutation and not inside the hook `useBridgeAction`. But we can refactor that in a separate PR.
Fixes ACX-1668
> fix: quote update after user connected wallet via bridge action button

- api/suggested-fees.ts
We should use getDefaultRelayerAddress() now because it contains conditional logic for which relayer to select based on the token being bridged.
> fix(suggested-fees): Defer default relayer assignment

- src/views/Bridge/components/AmountInput.tsx
When a user clicked the `MAX` button, the initial amount validation did not behave correctly.
> fix: display amount input error when clicking max button

- .env.example
REACT_APP_WALLET_CONNECT_PROJECT_ID is also required to run the project locally. Without it being present i got a while blank screen and now it loaded fine
> chore: add REACT_APP_WALLET_CONNECT_PROJECT_ID

- api/_utils.ts
- api/limits.ts
We should add `stale-while-revalidate` to our caching policy. The UX is improved by not requiring an unlucky user to request a fresh, uncached response. 
Additionally, we have boilerplate on all endpoints to return a response. We should centralize our returned headers. This PR adds a small response function that is tested in limits.
---
Requirements Fulfilled:
---
Partially closes ACX-1692
> fix: add stale-while-revalidate to limits

- src/utils/network.ts
Although the FE is reading from the `REACT_APP_VERCEL_ENV` - we're getting the instantaneous vercel API. We should check for a production API and force the `across.to` domain name.
> fix: enforce domain name on production environment

- src/utils/format.ts
- src/utils/tests/format.test.ts
The `formatUSD` didn't handle some edge cases correctly which led to a crash for small amounts.
> fix: `formatUSD` helper

- src/views/Bridge/components/AmountInput.tsx
The UI has a bug where it marks an empty input field with a red "please input positive number" error. The UI should go back to the unchanged state when a user removed their amount.
Steps to reproduce.
1. Visit `https://across.to/bridge`
2. Enter a number into the amount field.
3. Remove the amount entirely
You will be left with this:
> fix: only show invalid amt when there's an amount

- src/utils/constants.ts
- src/utils/providers.ts
We are redefining a list of chain ids when we have access to them already. This PR cleans up how we handle the initial instantiation of providers.
> improve: clean up providers.ts

- src/views/RewardsProgram/GenericRewardsProgram/GenericInformationCard.tsx
- src/views/RewardsProgram/GenericRewardsProgram/GenericRewardClaimCard.tsx
- src/views/RewardsProgram/hooks/useACXReferralsProgram.ts
This PR restores the claim tooltip when hovering over the clock icons below:
> improve: restore tooltip for claiming intervals

- src/views/Rewards/hooks/useRewardProgramCard.ts
- src/views/RewardsProgram/hooks/useGenericRewardClaimCard.ts
- src/views/RewardsProgram/hooks/useOPRebatesProgram.ts
There is a mixup with the amounts
> fix: op rebates claimable amounts

- src/views/Rewards/hooks/useRewardProgramCard.ts
This bug is a consequence of the Scraper API returning null rather than returning 0 for `unclaimedRewards` via the `/rewards/op-rebates/summary?userAddress={}` endpoint.
> fix: resolve crash when OP unclaimed reward is null

- src/utils/constants.ts
Goerli HubPool build was broken. This PR fixes it
> fix: add chain id 5 to external staking LPs const

- src/views/Bridge/hooks/useEstimatedTable.ts
Fixes base currency conversions on the fee preview for values > 1k. 
The root cause was again unexpected behavior of the helper `formatUSD`. I have seen quite a few bugs recently due to this function. From what I can tell, the function's naming suggests something else than it does. We should refactor the name soon.
> fix: base currency conversions for fee preview

- package.json
- scripts/generate-routes.ts
- src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json
- src/data/routes_5_0x0e2817C49698cc0874204AeDf7c72Be2Bb7fCD5d.json
The static `routes.json` files became hard to maintain with the recent additions of new chains/tokens. This PR adds a script to make future additions/removals easier.
> feat: utility script for generating static routes file

- src/utils/deposits.ts
Deposits with multiple fills, i.e. slow fills, were not correctly handled on the deposit confirmation screen.
> fix: correctly handle slow fills on deposit confirmation screen

- src/hooks/useLoadAmpli.ts
We think that default session events from Amplitude pollute the data on some of the dashboards. This PR disables them to see if this is the root cause.
> feat(ampli): disable default tracking of sessions

- src/components/DepositsTable/cells/NetFeeCell.tsx
The Scraper won't be able to distinguish the separate fee components of the total fee in v3 anymore (i.e. `lpFee`, `capitalFee` and `gasFee`). The fee breakdown will therefore only contain the `gasFee` certainly. This PR therefore uses that value to determine the details in the fee breakdown.
> fix: fee breakdown for v3 fees

- src/utils/deposits.ts
This PR fixes the V3 funds relayed event tracking in the deposit status page.
> hotfix(deposit-status): ensure v3 fills are read

- src/utils/deposits.ts
> fix: isV2 flag in log parser

- src/components/DepositsTable/DataRow.tsx
- src/components/DepositsTable/cells/ActionsCell.tsx
Users got confused when their deposits got delayed and tried to speed up. To prevent this in the future, we only allow speed up if the deposit is unprofitable and not delayed
> fix: only show speed up button if not delayed and unprofitable

- src/components/DepositsTable/cells/StatusCell.tsx
This PR fixes some obvious typos when there is not enough liquidity present to complete a bridge immediately.
> Fix typos in StatusCell.tsx

- vercel.json
Adds `/about` redirect to the marketing homepage.
> improve(vercel): redirects

- src/utils/format.ts
- src/views/Bridge/hooks/useEstimatedTable.ts
This PR aims to fix a bug related to the `estimatedBridgeTable` displaying discounted bridge fees after the 0.95 optimism program rebate is applied.
> hotfix(UI): parse units underflow

- src/views/Transactions/hooks/useSpeedUp.tsx
Related to ACX-1968. The actual fix was this PR though https://github.com/across-protocol/scraper-api/pull/362
The fallback `0x` masked the root cause. We therefore remove it in this PR
> fix: remove fallback message in speed up

- api/_constants.ts
SNX's relayer is making V2 Fill Estimates. We should defer to the ACX relayer address so that we can provide passing suggested-fees/limits endpoint calls.
> fix(snx relayer): temporarily move relayer support

- src/components/Footer/Footer.tsx
- src/views/Bridge/components/FeeInformationModal.tsx
- src/views/Rewards/components/AdditionalQuestionCTA.tsx
- src/views/RewardsProgram/hooks/useGenericRewardClaimCard.ts
Current docs links are out of date in several areas of the website. These broken links will lead to a 404 page on the Across gitbook.
> improve(docs link): correct updated docs

- src/utils/fill-times.ts
I opted not to add dummy values for Linea because they'd be wrong; better to flag that they need to be measured and added.
> fix(Linea): Permit undefined origin chain IDs in fill estimates

- package.json
- scripts/generate-routes.ts
- src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json
- src/utils/bridge.ts
- yarn.lock
Closes ACX-1977
New deployments of `SpokePoolVerifier` contracts use the old `deposit` function signature and is also compatible on Linea.
> feat: use new `SpokePoolVerifier` deployments

- api/_utils.ts
- api/limits.ts
- api/suggested-fees.ts
- test/api/_utils.test.ts
This PR removes querying the HubPools `SetPoolRebalanceRoute` events is order to resolve the token details. Instead, we use a static approach to improve performance.
> refactor(api): statically resolve token details

- src/views/Bridge/components/ChangeAccountModal.tsx
We should avoid selecting any disallowed wallets as recipients.
> improve(compliance): target disallow list in recipient

- api/_constants.ts
- api/_utils.ts
- api/suggested-fees.ts
- package.json
- yarn.lock
This PR implements the suggestion made by @pxrl [here](https://github.com/across-protocol/frontend-v2/pull/1000#pullrequestreview-1988379973) which removes the need to call `BlockFinder.getBlockForTimestamp` for the default case. This saves up ~ 3 sequential `getBlock` RPC calls which results in a 30-90ms speed-up. Also all `HubPool` contract calls are aggregated via mulitcall, which should decrease the opportunities for delayed RPC calls
Previously
Now
> refactor(api): optimize getblock call in fees handler

- api/_utils.ts
When we use `overrides`, in the multicall it requires an empty object. If the argument is `undefined` it throws 
```
Error: too many arguments: passed to contract (count=2, expectedCount=1, code=UNEXPECTED_ARGUMENT, version=contracts/5.7.0)
```
> fix: default to empty object when using `overrides`

- src/Routes.tsx
When redirecting, also pass query params on
> fix: bridge page redirect query params

- api/_utils.ts
- src/utils/constants.ts
- src/views/DepositStatus/components/DepositStatusUpperCard.tsx
We added testnet USDC routes for Arbitrum Sepolia and Optimism Sepolia but missed to add some constants.
> fix: add missing info for arbitrum + optimism sepolia

- .github/workflows/dependency-review.yaml
- api/_dexes/1inch.ts
- api/_dexes/types.ts
- api/_dexes/uniswap.ts
- api/_dexes/utils.ts
- api/_utils.ts
- api/swap-quote.ts
- package.json
- scripts/generate-routes.ts
- src/data/routes_11155111_0x14224e63716afAcE30C9a417E0542281869f7d9e.json
- src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json
- yarn.lock
Closes ACX-2016
We will use `epic/cctp` for testing, that's why the base branch for this PR is set to that.
Example request:
https://app-frontend-v3-git-swap-quote-endpoint-uma.vercel.app/api/swap-quote?depositor=0x9A8f92a830A5cB89a3816e3D267CB7791c16b04D&acrossInputToken=0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174&swapTokenAmount=100000000&originChainId=137&destinationChainId=10&acrossOutputToken=0x7F5c764cBc14f9669B88837ca1490cCa17c31607&swapToken=0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359
Note that I enabled the following swap route for testing purposes:
- `Native USDC (Polygon)` swap `Bridged USDC.e (Polygon)` bridge `Bridged USDC.e (OP)`
I am aware that this is not a route we want to support when we launch, but the closest route I could think of that fits our use case.
> feat(api): `GET /swap-quote` endpoint

- scripts/generate-routes.ts
- src/data/routes_11155111_0x14224e63716afAcE30C9a417E0542281869f7d9e.json
- src/views/Bridge/hooks/useSelectRoute.ts
- src/views/Bridge/utils.ts
This enables missing USDC routes on Base and OP Sepolia:
- `normal bridge routes`
- native USDC -> USDC.e/USDbC
- `swap routes`
- USDC.e/USDbC -> native USDC
- USDC.e/USDbC -> USDC.e/USDbC
> feat: enable missing native/bridged usdc routes on sepolia

- api/available-routes.ts
Requested by integrators to add token symbols to `/available-routes` response
> feat: add token symbols to `/available-routes` response

- src/utils/index.ts
- src/utils/url.ts
- src/views/DepositStatus/components/DepositStatusLowerCard.tsx
- src/views/DepositStatus/components/DepositTimesCard.tsx
While QAing different deposit routes, it was a bit annoying that the query params from the previous deposit were not preserved.
> feat: preserve bridge url query params when initiating new tx

- src/utils/constants.ts
- src/views/Bridge/hooks/useBridge.ts
I noticed a few swaps that were reverting on Polygon. Probably due to too low slippage? But in case we want to change it dynamically, I prepared this PR to override via env var.
> feat: make default swap slippage configurable

- api/limits.ts
Technically, `recommendedDepositInstant` is a hardcoded value that can be greater than `maxDepositInstant` during times of volatility. We may want to limit the `recommendedDepositInstant` to the maximum deposit that can be filled without a slow fill.
> fix(recommendedDepositInstant): floor as needed

- api/limits.ts
- api/suggested-fees.ts
- package.json
- yarn.lock
Required changes in /limits and /suggested-fees endpoints to support Across Lite.
/limits: when the requested route involves a lite chain, we avoid including the LP balances when defining limits.
/suggested-fees: the LP fee must be 0 when a route involves a lite chain. To achieve that we conditionally overwrite the rate model key we query.
> feat: Across Lite support in /limits and /suggested-fees endpoints

- api/_utils.ts
- api/liquid-reserves.ts
Currently relayers query /limits to figure out the `maxDeposit` they should fill, however `maxDeposit` currently applies a buffer which means the relayer can't fill any deposits that are larger than the `liquidReserves * buffer` but smaller than `liquidReserves`
Create a separate endpoint with a simpler interface (i.e. only need to define L1 token and origin chain ID and both are required params) to get limits for relayer. This should simplify the relayer code in the AcrossApiClient
Signed-off-by: nicholaspai <npai.nyc@gmail.com>
> feat(liquidReserves): Add liquid-reserves endpoint that relayers can use

- api/_constants.ts
- api/_utils.ts
Due to an upgrade, we can no longer rely on the balancer-hosted subgraph to fetch the pool data. We need to use a new on-chain subgraph, which requires us to hardcode the URLs for each required subgraph. The caveat is that we now need an API key to access the subgraphs.
> hotfix(wsteth-acx): resolve underlying subgraph error

- package.json
- yarn.lock
Constants now includes an ETH address for Polygon. This is an implicit requirement due to the way some address -> token resolution functions work.
> fix(Amoy): Bump constants & SDK

- api/limits.ts
Closes ACX-2294
The env vars for the limits multipliers are also adjusted. We still need to set up some schedulers to keep the cache fresh for major routes so that performance is not impacted too much as suggested by @mrice32
> feat: decrease /limits cache time

- api/_constants.ts
- api/_utils.ts
- api/limits.ts
- package.json
- src/utils/typechain.ts
- yarn.lock
Bumps to latest @across-protocol deps and fixes some bugs discovered while adding support for Lisk and Blast.
> feat: bump packages + testnet fixes

- api/suggested-fees.ts
These fields will be placeholders to allow integrators/frontends to begin taking suggested exclusivity parameters and passing them into their deposit calls.
> feat: add exclusivity parameters to /suggested-fees

- src/utils/config.ts
Introduce the Arbitrum merkle distributor address so the FE can configure the claiming txn
> chore: use arb reward addresses

- api/_utils.ts
Inherit same gas markup for OP Stack chains if not explicitly set as env var
> feat: better gas markup fallback for op stack chains

- api/coingecko.ts
- yarn.lock
We previously allowed a case where we could quote a price with a non-standard base currency. I.e. `acx/wbtc` was possible.
This is out of scope of existing work and no longer needed. Removing will improve readability, clean up legacy code, and make additional changes to this API endpoint more convenient.
> improve(api): remove some unneeded scope

- api/_constants.ts
- api/coingecko.ts
Missed reference to matic in suggested-fees. This enabled a _select_ number of derived tokens.
> hotfix(coingecko): account for derived currencies with strict scope

- src/components/DepositsTable/DepositsTable.tsx
- src/components/DepositsTable/HeadRow.tsx
- src/utils/math.ts
- src/views/Bridge/components/EstimatedTable.tsx
- src/views/Bridge/components/FeesCollapsible.tsx
- src/views/Bridge/hooks/useEstimatedRewards.ts
- src/views/DepositStatus/components/DepositStatusLowerCard.tsx
Rewards are now capped to `min(25bps, bridge_fee) * 95%`. UI has had updates to reference this information.
> improve(rewards): cap estimation at 25bips of input

- src/views/Bridge/hooks/useBridge.ts
Fixes ACX-2425
We displayed the previously quoted max. deposit limits if a user swapped chains for example. This PR fixed that issue by only displaying the quoted limits if a transfer quote could be retrieved
> fix: display correct max deposit limits value

- api/_timings.ts
SNX relayer has been online again for a while. We can remove overrides
> chore: remove snx fill time override

- api/_timings.ts
We can assume there's a possibility our descending routes fail. This new logic eventually lands us at 10 seconds if we have no specific definitions
> fix: more robust undefined checking

- src/hooks/useUnclaimedProofs.ts
- src/utils/merkle-distributor.ts
Currently the `Claim` button is enabled because of proofs that corresponds to windows that were not created yet. 
This PR will allow to claim rewards only for the proofs that are associated with windows that were created in the MerkleDistributor contract
> fix: don't claim rewards for windows not live

- src/views/Bridge/components/BridgeForm.tsx
- src/views/Bridge/components/EstimatedTable.tsx
- src/views/Bridge/components/FeesCollapsible.tsx
- src/views/Bridge/utils.ts
We were displaying the message "Input amount exceeds limits set to maintain optimal service for all users. Decrease amount to 0 LSK or lower." when maxDeposit was 0.
> fix: update UI message when maxDeposit is 0

- api-docs-openapi.yaml
There seems to have been an update in [Scalar](https://github.com/scalar/scalar) (the API client used when clicking `try it` in GitBook) which broke the default values for query params. This PR tries to fix it.
> docs: fix try-it section default values

- api/_constants.ts
- api/_utils.ts
This consolidates the ENV vars related to relayer quoting override to a single ENV with the structure: 
```
{
defaultAddr?: string;
symbols?: {
[symbol: string]: {
defaultAddr?: string;
chains?: { [chainId: string]: string };
};
};
}
```
> improve: consolidate ENV vars

- api/account-balance.ts
high demand for weth bridges are causing relayers' balances to be wiped out quicker than usual, therefore we need to decrease the time we cache balances for
> chore: cache balance for 1 minute

- .gitignore
- api/_utils.ts
- scripts/pre-build.ts
- scripts/remote-configs/utils.ts
- src/data/examples/rpc-providers.json
~Requires #1175~
Closes ACX-2586
Uses configs set in here https://github.com/UMAprotocol/across-configs/blob/master/packages/quotes-api-config/config.json. This allows for a workflow similar to the `fill-times.json` and bot configs.
> feat: use rpc provider configs from remote

- api/_utils.ts
Since we started using our custom `RetryProvider` in the API, we can not use `provider.connection.url` anymore because this resolves to `localhost:8545`. This broke the Balancer pool handler. We fix this by using the provider URL from the config JSON directly.
> fix: use rpc url from config json in balancer handler

- api/_utils.ts
Retry delay in `RetryProvider` was set to high
> fix: use retry delay as seconds

- api/_exclusivity/index.ts
All SpokePools have been upgraded now.
This reverts commit 9c5cc82f0f5ff378596212f6bce18e5f0a9fadaa.
> Revert "fix(exclusivity): Reintroduce origin chain constraint (#1188)"

- api/_utils.ts
I have seen higher volatility between execution times since the last commit. Trying to figure out if the max concurrency is the issue
> fix: reduce max concurrency

- api/_utils.ts
The API is throwing a lot of the following errors that can be reproduced locally
```
InputError: Relayer fill simulation failed - processing response error: SERVER_ERROR
at getRelayerFeeDetails (/vercel/path0/api/_utils.ts:632:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Promise.all (index 0)
at handler (/vercel/path0/api/limits.ts:132:9)
at async Server.<anonymous> (/opt/rust/nodejs.js:1:10566)
at async Server.<anonymous> (/opt/rust/nodejs.js:8:4242)
END RequestId: a7503f75-c737-4371-8c1b-2fb7f27a55bb
REPORT RequestId: a7503f75-c737-4371-8c1b-2fb7f27a55bb	Duration: 6585.34 ms	Billed Duration: 6586 ms	Memory Size: 1024 MB	Max Memory Used: 377 MB
```
Hope to get more insight with this change
> feat: improve ethers error parsing in API

- api/_utils.ts
Since the introduction of cached values, we have been seeing a lot API errors like
```
InputError: Relayer fill simulation failed - processing response error: SERVER_ERROR - Error: failed with 50044019 gas: max fee per gas less than block base fee: address 0x07aE8551Be970cB1cCa11Dd7a11F47Ae82e70E67, maxFeePerGas: 14025000, baseFee: 19815000
at getRelayerFeeDetails (/vercel/path0/api/_utils.ts:632:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at handler (/vercel/path0/api/suggested-fees.ts:255:31)
at async Server.<anonymous> (/opt/rust/nodejs.js:1:10566)
at async Server.<anonymous> (/opt/rust/nodejs.js:8:4242)
END RequestId: 60797827-296d-4bde-af4a-8862b3692f0e
REPORT RequestId: 60797827-296d-4bde-af4a-8862b3692f0e	Duration: 7303.97 ms	Billed Duration: …
```
> fix: temp ignore cached gas price

- api/_utils.ts
- api/suggested-fees.ts
Test WIP in the preview links to confirm logging
> fix: suggested-fees min amounts

- api/limits.ts
It's easier to maintain this value if we set a global USD min default and allow it to be overridden per chain
> improve(limits): Allow developer to set minDepositUSD

- api-docs-openapi.yaml
We should document that /limits is returned in the suggested-fees response
> feat: Add Limits to suggested-fees open-API docs

- api/_cache.ts
- api/_utils.ts
- api/limits.ts
- api/suggested-fees.ts
Add the following optional parameters to `/limits` to make it possible to compute the exact same limits in suggested fees:
- message
- recipient
- relayer
- amount
This way the `/suggested-fees` endpoint can query `/limits` using those parameters so it doesn't need to recompute `relayerFeeDetails()` which might return very different values.
I believe this also removes the need for `relayerFeeDetails` to compute the `isAmountTooLow` boolean anymore.
> feat(API): Align limits and suggested-fees relayerFeeDetails computations

- api/_utils.ts
- api/limits.ts
- api/suggested-fees.ts
- package.json
- yarn.lock
Closes ACX-2429 and ACX-2610
This PR introduces more potential speed improvements:
1. Usage of [SpeedProvider](https://github.com/across-protocol/frontend/compare/more-speed-improvements?expand=1#diff-428e8c9eb80e1971d1eb1d20244ebe4791f3f5d6c6c664cb694759f503874251R793-R800) 
2. Caching of fill gas units
3. ~Re-introduction of using cached gas price with tweaked params~ EDIT: Will be postponed to separate PR
4. Usage of cached token balances from redis instead of self call
> perf: api speed improvements

- api/available-routes.ts
- api/suggested-fees.ts
This enhances routes with some additional useful information
> feat(api): add spoke pool addresses to available-routes

- api/_cache.ts
- api/_utils.ts
- api/account-balance.ts
- api/cron-cache-balances.ts
- vercel.json
This PR introduces a cron-scheduled handler that aims to keep relayer balances for all tokens on all chains fresh. Theoretically, this should further even out worst-case latencies for /limits and /suggested-fees.
Closes ACX-2661
We could use a similar approach for fairly constant and static values as well, such as `gasPrice`, `fillGasExpenditure`, `latestBlock`, etc. One issue is that Vercel only supports a min. interval of minutes. So for TTL values that are in seconds, we would need to create another external trigger
> perf: cron job for caching relayer balances

- api/suggested-fees.ts
We don't need to expose the relayer fee details in the `suggested-fees.limits` field due to redundancy
> chore: remove redundant relayer fees from nested limits field

- api/limits.ts
Cached gas units should only be used for standard bridges with constant gas expenditures
> fix: only use cached gas units if message empty

- src/components/DepositsTable/cells/ActionsCell.tsx
- src/components/DepositsTable/cells/StatusCell.tsx
- src/components/DepositsTable/hooks/useDepositStatus.ts
Expired deposits no longer display a infinite loader next to the `Expired` status + are ineligible for the speedup modal.
> fix: resolve speedup requests on expired deposits

- api/_exclusivity/index.ts
- api/batch-account-balance.ts
Fixes ACX-2700
I noticed a few 500 response codes in our monitoring tool when calling /suggested-fees. It seems that these happen when exclusivity is set but there is no relayer opted in for a specific origin chain
> fix: handle empty addresses query param

- api/suggested-fees.ts
This exisiting logic can return an exclusive relayer with exclusivityDeadline 0, which is a no-go for depositV3().
> fix(exclusivity): Require depositMethod=depositExclusive for exclusivity

- api/_utils.ts
- api/swap-quote.ts
Running `yarn lint` uncovered 3 small issues - all unused vars. This PR resolves the linter warnings.
> fix: linting issues

- api/_errors.ts
- api/_utils.ts
- api/cron-cache-balances.ts
- api/cron-cache-gas-prices.ts
- api/limits.ts
- package.json
- vercel.json
- yarn.lock
> perf(api): cache gas price

- api/_utils.ts
- api/batch-account-balance.ts
- api/chains.ts
closes ACX-2842
- allows consumer to filter /chains response by list of chainIds. this means the sdk can easily retrieve and cache chain specific data (spokePool address etc.)
> allow filtering by chainId or list of chainIds

- api/_timings.ts
To fully exclude https://github.com/across-protocol/frontend/pull/1215 as the cause for the degraded API performance, temp revert change and monitor impact on speed.
> fix: revert fill time refactor to test perf impact

- api/_utils.ts
- src/utils/bridge.ts
If the host time is out of sync with the origin chain time then it may be possible to set fillDeadline such that it would revert on simulation. Per existing implementation, this could occur if the RPC time was > 60 seconds behind the host time, or if the host time was > 60 seconds ahead. Using the time of the chain and the fillDeadlineBuffer offset should protect against this possibility.
> improve: Isolate host time from deposit fillDeadline

- api/_utils.ts
- api/limits.ts
- package.json
- yarn.lock
- Bump to sdk version which returns unpadded gas units
- Decrease limits response cache TTL to minimize stale gas values
> fix: cached gas units

- package.json
- scripts/generate-routes.ts
- src/components/AmountInput/AmountInput.tsx
- src/data/chains_1.json
- src/data/chains_11155111.json
closes ACX-2707
- find the relative path of the logo in `chainConfig` and resolves it. testnet chains do not have duplicate assets so this will direct base-sepolia to base/assets/logo.svg. 
- directories for multi word names use dashes (-) as separator, while we export the chainConfig map keys with underscores. when resolving the path we need to replace underscores with dashes. this fixes the zksync logo resolution
> fix casing of zksync logo served from /chains

- scripts/generate-routes.ts
- src/data/chains_1.json
- src/data/chains_11155111.json
Some integrators using our /chains endpoint noticed tokenLogos don't resolve for USDC.e for example.
> serve logos for bridged usdc

- api/_errors.ts
- api/_utils.ts
closes ACX-3284
While calculating swap routes using uniswap's sdk, we need to find the token symbol and decimals for any token address on any chain,
Since there is no on-chain way of getting the token symbol for a native token, we need to use an external api. we can use that exposed by chainlist.org and cache any values for a pretty long ttl.
> get token details for any address in any chainId

- api/_constants.ts
- api/_utils.ts
- api/coingecko.ts
- package.json
- test/api/_utils.test.ts
- yarn.lock
Taken from #1265 - this enables the new SDK code that can handle AZERO being queried as a valid price. The relayer can/should be able to use this process fills without needing to publish #1265 now.
> feat: non-eth price lookup support

- api/_dexes/cross-swap.ts
- api/_dexes/types.ts
- api/_dexes/uniswap.ts
- api/_integrator-id.ts
- api/_utils.ts
- api/swap.ts
- scripts/tests/swap.ts
Closes ACX-3286
This adds cross swap tx building. Here are some example tx for the different cases:
| type | deposit tx                                                                                       | fill tx                                                                                         |
| ---- | ------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------------------------- |
| B2B  | [Tx](https://basescan.org/tx/0x0a59e3ae526c7b03b2c547d0f84e93e1cb8c6c4536d5e31de2cee26f73ae6c57) | [Tx](https://arbiscan.io/tx/0x65a60f7b20248d435ce85b7a4532c12227ba38d81bbebc114c3420e10f57c312) |
| B2A  | [tx](https://basescan.org/tx/0x4aa4d03c9d5e9bf800852b76290f74fe90810469d3 …
> feat: build cross swap tx

- src/components/AmountInput/AmountInput.tsx
- src/views/Bridge/Bridge.tsx
- src/views/Bridge/components/AmountInput.tsx
- src/views/Bridge/components/BridgeForm.tsx
- src/views/Bridge/hooks/useBridge.ts
- src/views/Bridge/utils.ts
This PR unblocks the user from depositing if the suggested fees pct is > 5bps. It still shows a warning like in the screenshot below:
> feat: add unblocking warning-level input validation

- api/_dexes/cross-swap.ts
- api/_dexes/types.ts
- api/_dexes/uniswap/adapter.ts
- api/_dexes/uniswap/quote-resolver.ts
- api/_dexes/uniswap/swap-router-02.ts
- api/_dexes/uniswap/trading-api.ts
- api/_dexes/uniswap/universal-router.ts
- api/_dexes/uniswap/utils.ts
- api/_errors.ts
- api/_spoke-pool-periphery.ts
- api/_utils.ts
- api/swap/_utils.ts
- api/swap/allowance.ts
- scripts/generate-routes.ts
- scripts/tests/swap-allowance.ts
- src/data/routes_1_0xc186fA914353c44b2E33eBE05f21846F1048bEda.json
Closes ACX-3382
Sorry for the big PR but had to refactor quite a lot to support the Trading API and `UniversalRouter`. This PR allows the usage of different quote resolving + tx building strategies. We also make use the trading API for improved performance.
Note that it is possible to use the Uniswap API to retrieve a quote and use the old SwapRouter02 implementation to build the respective tx. One problem we need to address is the requirement for permit2 support when using the UniversalRouter contract.
> feat: use trading api + support universal router

- vercel.json
The cron job works but leads a `Gateway Timeout` because the default exec time is 15 sec. Bump to 60 seconds.
> fix: cron ping endpoints

- src/views/Staking/Staking.tsx
- src/views/Staking/components/StakingForm/StakingForm.styles.tsx
- src/views/Staking/components/StakingForm/StakingForm.tsx
- src/views/Staking/components/StakingReward/StakingReward.tsx
- src/views/Staking/types.ts
If on the staking page with the wrong network in your wallet, clicking the button fails silently. This PR fixes it
> fix: network switch in staking/rewards

- src/views/Bridge/utils.ts
To drop the warning on `yarn lint`
> nit: remove unused vars

- src/components/DepositsTable/hooks/useDepositStatus.ts
Currently we have a case where if a deposit takes longer than 5 minutes and is larger than the max deposit instant then we display a 3-hour warning. This change updates the deposit to only mark delay if the deposit amount is larger than the max deposit short delay
> improve: reduce edgecase on delayed deposits

- api/_exclusivity/cache.ts
For testing purposes we should keep these values able to be removed
> chore: set tight ttl on relayer config

- api-docs-openapi.yaml
This encourages integrators to work around the limit. Better to have it fail and let them reach out.
> chore: Drop max message length description

- src/utils/bridge.ts
- src/utils/constants.ts
> use fill deadline buffer from env

- api/_dexes/utils.ts
- api/_permit.ts
- api/_spoke-pool-periphery.ts
- api/_utils.ts
- api/relay/_utils.ts
- api/relay/index.ts
- api/swap/_utils.ts
- api/swap/approval/_utils.ts
- api/swap/permit/_utils.ts
- api/swap/permit/index.ts
- scripts/tests/_swap-utils.ts
- scripts/tests/swap-allowance.ts
- scripts/tests/swap-permit.ts
> feat: base handler for `POST /relay`

- package.json
- src/utils/onboard.ts
- yarn.lock
Adds explicit _connectors_ for both Phantom and Metamask. 
Currently web3onboard only shows connect buttons for any injected connector it detects is present in the browser.
This change adds a deeplink for either the extension or the mobile wallet if the user is visiting via a browser with no injected connector (chrome on mobile).
> add explicit connectors for metamask and phantom

- CODEOWNERS
The syntax used in the codeowners file that was just committed differs slightly from the github canonical syntax.
- They use a preceding / for root of the repo. Not sure if this is implicit if you drop it, but this is corrected to be safe.
- api/* would only apply to files in the api directory, not to files in subdirectories. This is fixed by dropping the *.
Sorry for the confusion, I should have checked the syntax more carefully!
Feel free to merge once approved.
> fix: correct codeowner file syntax

- src/views/Bridge/utils.ts
We were essentially referencing non native ETH chains but in two places. This will make new chain automation more concise.
> improve: rely on nonEthChains constant for initial routes

- api/_eip712.ts
- api/_permit.ts
- api/_transfer-with-auth.ts
- api/swap/_utils.ts
- api/swap/approval/_utils.ts
- api/swap/approval/index.ts
- api/swap/auth/_utils.ts
- api/swap/auth/index.ts
- api/swap/index.ts
- api/swap/permit/_utils.ts
- api/swap/permit/index.ts
- scripts/tests/_swap-utils.ts
- scripts/tests/swap-allowance.ts
- scripts/tests/swap-auth.ts
- scripts/tests/swap-permit.ts
- scripts/tests/swap-unified.ts
This cleans up a few things and aligns swap response formats to be consistent. Also adds a test script for the unified swap endpoint
> refactor: cleanup + align swap response formats

- package.json
- yarn.lock
Gas prices will be more accurate for OP stack chains and also for Zora which was mistakenly removed from the OPStack family prior to this SDK bump
This is a lower risk PR to merge in before https://github.com/across-protocol/frontend/pull/1339 to isolate certain chains where we can get more accurate gas estimation without including the new multiplier logic in #1339
> improve: Update SDK version to 3.3.30 to get access to more accurate gas prices

- api/_utils.ts
- api/cron-cache-gas-prices.ts
- api/gas-prices.ts
- api/limits.ts
- package.json
- yarn.lock
This PR contains several optimizations that ultimately make the `gasFeeTotal` as accurate as possible while ensuring that the `/limits` endpoint is retrieving gas fee components from the cache as often as possible, keeping the endpoint latency down.
We can reduce the /limits endpoint cache time to 1s while the revalidate period is 59s so that after the cached value is >1s old we can immediately start recomputing the limits value. This means in the best case we'll have as fresh gas cost data as possible--essentially, as quickly as we can re-compute the gas fee totals.
We should ideally use less stale gas price data. This PR reduces the gas price caching time to 10s from 5s.
We currently cache the entire `tokenGasCost` value but this means we are negating some of the optimizations we have …
> improve(API): Make gasFeeTotal more accurate in /limits and increase cache hit frequency

- api/_types/utility.types.ts
- api/cron-cache-gas-costs.ts
- api/cron-cache-gas-prices.ts
- api/cron-cache-l1-data-fee.ts
- vercel.json
Updating the gas costs and gas prices in the same cron job makes the cache resets slower due to the memory constraints of a single file, and when updating the gas price every 5s, this makes a difference.
This PR splits the gas cost updates, which are 10s and 30s for l1 data fees and native gas costs, separate from the gas price updates so that the gas price updates can be closer to 5s. Currently its anywhere from 5s to 10s.
Additionally, this PR adds try-catches around the `await cache.set()` calls so that the a failure due to an upstream RPC call (e.g. I've seen this happen with linea_estimateGas calls a lot) doesn't take down the cron job for the full run.
Finally, there was an issue with the current cron job where all combinations of chainId+outputToken were repeated many times, …
> feat(API): Split gas component cron jobs up into different files

- api/_utils.ts
In case developer forgets to set fee markups explicitly, set more reasonable defaults such that the default suggested fees are conservative enough to avoid relayers from viewing the quotes as unprofitable.
> improve(API): Change default fee markup values to be more developer-friendly

- src/hooks/useBridgeFees.ts
- src/utils/bridge.ts
- src/utils/hyperliquid.ts
- src/utils/query-keys.ts
- src/utils/serverless-api/mocked/suggested-fees.mocked.ts
- src/utils/serverless-api/prod/suggested-fees.prod.ts
- src/utils/serverless-api/types.ts
- src/views/Bridge/hooks/useBridgeAction.ts
- src/views/Bridge/hooks/useTransferQuote.ts
This update sets the fees more accurately by calling into the suggested fees API endpoint with a simulated message payload. 
~~The caveat here is that due to rounding issues there's sometimes a 1 unit refund against the recipient (0.000001 USDC). Examples:~~
~~* https://arbiscan.io/tx/0x0ad884bf8eadcda92a2ad3fc55d62d79bac30ac80c83f0d0c32e04b06e8ace56~~
~~* https://arbiscan.io/tx/0xc800914ff0d79bc6c5032abfe3a90cfbd35c48109420b1d0f1b04d4720dab0f5~~
> feat(hyperliquid): estimate fees properly

- scripts/generate-routes.ts
- src/data/routes_11155111_0x14224e63716afAcE30C9a417E0542281869f7d9e.json
- src/utils/config.ts
When bridging from a chain with a custom gas token (e.g. GRASS Lens Sepolia), the dApp was not correctly handling it as a native token.
> fix: custom gas token bridging

- src/utils/bridge.ts
The logic change is in an area that simulates a suggested fees message payload. In an unconnected state the fallback recipient is undefined and this causes a failure.
> hotfix(hyperliquid): quote on unconnected wallet

- .github/dependabot.yml
- package.json
- src/components/GlobalStyles/GlobalStyles.tsx
- src/views/Staking/hooks/useStakeFormLogic.ts
- yarn.lock
Some deps should be ignored by dependabot. This could be due to:
- Not using SemVer
- Pinning to a specific version
> ci: add deps to dependabot ignore list

- src/hooks/useAvailableRemainingRewards.ts
We want to end the program at 749K OP so we have 1K OP available in case we need them for deposits that didn't get the expected rewards.
> chore: update OP ceiling to end rewards program

- src/hooks/useBridgeFees.ts
We cannot initiate slow fills for Hyperliquid due to protocol constraints preventing slow fills on messages. Therefore, we need to gracefully handle this in the UI by not showing a quote and not hanging.
> fix: account for message requirement on relayer balance

- src/views/Bridge/hooks/useTransferQuote.ts
The fee query when switching from Arbitrum to HL didn't always update. Even though the fees query got recomputed, the quote query did not.
> fix: recompute fees when switching arb <-> hl

- api/_utils.ts
- api/cron-cache-l1-token-configs.ts
- api/suggested-fees.ts
- vercel.json
This adds some fallback logic to the API in case of an un-parsable JSON. We have a CRON job which runs every hour to cache parseable L1 token configs. If we fail to parse the string directly fetched from the ConfigStore, we use the cached one.
> feat: l1 token config fallback

- api/_utils.ts
- scripts/generate-ui-assets.ts
- src/constants/chains/configs.ts
- src/utils/providers.ts
In the dApp always use public RPCs and introduce new env var to override if necessary. In the API use ones from remote config JSON or public one as fallback.
> fix: new custom rpc url namespace in dApp

- api/_utils.ts
We need to be able to set max balances for a set of tokens on ALL chains per environment, testnet 
We can do this with env var `CHAIN_USD_MAX_DEPOSITS`
this will set a $10 max deposit for all chains for USDC,WETH,ETH 
`CHAIN_USD_MAX_DEPOSITS="{"*":{"USDC":"10","ETH":"10","WETH":"10"}}"`
> match wildcards for max deposits env var

- api/_constants.ts
- api/_relayer-address.ts
- api/_utils.ts
- api/cron-cache-balances.ts
- api/limits.ts
- api/suggested-fees.ts
Closes ACX-3891
Allows to set new env var `TRANSFER_RESTRICTED_RELAYERS` in the format
```
{
"1135": {
"LSK": "0x..."
}
}
```
> feat: allow setting transfer restricted relayer per chain and token

- src/utils/sdk.ts
- src/views/Transactions/hooks/useSpeedUp.tsx
We are moving to version-generic event names. We should move forward with using the generic speed-up deposit fn.
Note: this is an opinionated change
> improve: use generic speed up txn

- src/views/Bridge/utils.ts
We have the ability to set default IN/OUT tokens for a given chain route.
Currently only works when user actively changes route parameters.
This sets the token defaults on INITIAL route also.
> use token default on initial route

- src/views/Bridge/utils.ts
If a user is connected to mainnet, the app finds the next best enabled route where mainnet is origin chain. 
Currently this is TO Lens. 
This PR sets Arbitrum as the default destination chain
closes ACX-4054
> fix: set arbitrum as the default destination chain

- api/_constants.ts
- package.json
- yarn.lock
Part of https://github.com/across-protocol/sdk/pull/997
Adds support for env var `RELAYER_FEE_CAPITAL_COST_DESTINATION_CHAIN_OVERRIDES`
renames ~~`RELAYER_FEE_CAPITAL_COST_OVERRIDES`~~ => `RELAYER_FEE_CAPITAL_COST_ROUTE_OVERRIDES`
> feat: support destination chain relayer fee calculator config overrides

- src/components/DepositsTable/cells/StatusCell.tsx
- src/hooks/useDeposits.ts
**Issue**
We are not handling correctly the `StatusCell` for deposits with slow fill requests and the dApp fallbacks to show them as `filled`
> fix(hotfix): fix status cell for slow fill requested deposits

- src/hooks/useDeposits.ts
- src/views/Transactions/components/PersonalTransactions.tsx
`depositTransactionHash` and  `fillTransactionHash` are being renamed in the `/deposits` indexer endpoint
> fix: fix indexer deposit fields

- src/hooks/useDeposits.ts
- src/views/Transactions/components/PersonalTransactions.tsx
Fill transaction hash missing in transactions table
> fix: add fill tx in transactions table

- api/_constants.ts
Required by the relayer because it queries the production API endpoint for prices.
> chore: add vlr to cg deferred id

- api/limits.ts
- api/suggested-fees.ts
- package.json
- yarn.lock
This [PR](https://github.com/across-protocol/frontend/pull/1610) was rolled back due to some remaining issues when `allowUnmatchedDecimals=true`.
During my investigation, I found that after this was merged, error rates on BTC transfers to linea would spike. This is because [this line](https://github.com/across-protocol/frontend/blob/cb9c47cf149d8ecba7dab0542f17b62c1943be91/api/limits.ts#L110) is being activated, causing the limits API to assume that at least one unit of the currency is held on the destination chain by the simulated relayer. This is a problem for BTC.
I also found another issue in how the response is being constructed when testing. In `/suggested-fees`, the `relayerCapitalFee.total` and `relayerGasFee.total` were being scaled to the output token's decimals, but the …
> fix: limits failures and decimal inconsistency

- api/_cache.ts
This PR creates a separate cache namespace for all `preview` deployments by default, which can still be overridden by setting the environment variable `CACHE_PREFIX` for a specific branch or deployment.
Alternatively, the default for previews could be the deployment URL. Not 100% which makes more sense
> fix: default separate cache namespace for preview/prod

- .github/workflows/lint-test.yaml
- package.json
This PR makes 3 small changes to our `lint-test` workflow.
1. Adds a new job: `api-tests` which runs `yarn test-api`. I added this because the current configuration only runs frontend unit tests and skips the API tests.
2. Combines `yarn format` and `yarn lint` into a single run step.
3. Removed unnecessary second `yarn format`. Since linting will not change any file contents, I don't believe we need a second format.
To verify that adding `yarn test-api` to our workflow won't break anything, I ran it locally and the current tests passed. The next step is to add more coverage.
> ci: add job for API tests

- src/hooks/useConnection.ts
- src/hooks/useIsContractAddress.ts
- src/views/Bridge/hooks/useToAccount.ts
- src/views/DepositStatus/components/DepositStatusLowerCard.tsx
- Suppress the red warning banner when the depositor is a 7702 delegation on the origin chain.
- When the recipient on the destination chain has a 7702 delegation in place, ensure that the outputToken is shown as WETH and not ETH.
Fixes ACX-4114
> fix: handle 7702 correctly

- api/_utils.ts
- api/limits.ts
- api/suggested-fees.ts
This PR fixes the relayer gas fees that the API would compute:
- Consider the `recipient` address always when dest. chain is Solana
- This is required because the recipient might need a PDA or ATA set up if not existent
- Use correct native token decimals for `RelayFeeCalculator`
- [Correct `/limits` response](https://app-frontend-v3-git-fix-recipient-address-gas-costs-uma.vercel.app/api/limits?inputToken=0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913&outputToken=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&originChainId=8453&destinationChainId=34268394551451&allowUnmatchedDecimals=true&amount=2000000&recipient=B9mvTvYZuoEjLtxtNun2r2jmcmYCCJp2uwt1o8tpFfm7)
- [Wrong `/limits` response](https://app-frontend-v3-git-epic-solana-v1-uma.vercel.app/api/limits?inputToken=0x833589fCD6eDb6E08f4c7C32D4f7 …
> fix: relayer gas fees for solana

- api/_dexes/uniswap/utils/trading-api.ts
- api/coingecko.ts
There were two issues in the /swap endpoint that would lead to 502s returned:
1. The Multicall3 address is blocked by Uniswap's Trading API. We circumvent this by using a dummy address to retrieve a quote but when constructing the swap tx, we use the correct address.
2. For some requests, the coingecko endpoint would throw 508 LOOP_DETECTED errors. I could narrow it down to cases where we would self-call the coingecko endpoint for derived currencies. We fix this by factoring the logic into a separate function. This might have a slightly negative performance impact.
> fix: blocked address uni trading api + loop detected error

- src/hooks/useDeposits.ts
This PR updates the `/deposits` query to use `address` instead of `depositor`, this way the indexer returns deposits where the address is either the depositor or the recipient, rather than just the recipient.
Note: this is the way it used to work with the scraper.
> fix: use address instead of depositor when querying deposits

- api/pools-user.ts
- src/views/LiquidityPool/components/ActionInputBlock.tsx
closes ACF-21
- We no longer cache responses from `/api/user-pools` on the server. This stale data is causing UX issues in the frontend.
- We also explicitly refetch users' LP token balances after a successful withdrawal/deposit into an LP.
> don't cache user pool value

- vercel.json
PancakeSwap reported delays in reflecting the deposit status correctly in our API. I was able to replicate the issue and what happened was that `https://indexer.api.across.to` had the status updated, but `https://app.across.to` returned `404 Deposit not found`. This led me to think that there's a caching issue, so I am disabling caching for all Indexer API endpoints.
> fix: disable indexer api cache

- src/hooks/useWalletSorted.ts
closes ACX-4186
We were using evm standard of detecting which wallets are installed in the browser leading , so wallets other than those which are compatible on BOTH evm and svm, were not shown as installed.
Use Solana's baked-in wallet adapter logic to detect if wallets are installed.
##Note
the 2 Metamask options are technically 2 separate wallets. 
One is the Solflare plugin within Metamask.
The other is Metamask's own native SVM wallet.
This is intentional and Metamask "Emits" both wallets as being available options to the dapp.
> Fix SVM Wallet selector 

- api/_dexes/cross-swap-service.ts
- api/_dexes/utils.ts
- api/_utils.ts
- test/api/_dexes/utils.test.ts
As mentioned in [ACX-4169](https://linear.app/uma/issue/ACX-4169/determine-dynamically-a2b-or-b2a-based-on-lowest-fees):
>Currently if the inputToken AND the outputToken are bridgeable and not the same asset (e.g. OP USDC -> Arb ETH), we prefer origin swaps over destination swaps
>We need to fetch quotes for both possible routes (origin swap + bridge OR bridge + destination swap) and return the cheapest
- Make `getCrossSwapTypes` return a list of possible cross swap types.
- **If the input and output tokens are bridgeable AND do not have an enabled route**, return both `CROSS_SWAP_TYPE.ANY_TO_BRIDGEABLE` and `CROSS_SWAP_TYPE.BRIDGEABLE_TO_ANY` as a list.
- Add new function `selectBestCrossSwapQuote` which does the following:
- Call `await Promise.allSettled` on all the possible cross swap …
> feat: select best quote based on all possible cross swap types

- api/_errors.ts
- api/_types/generic.types.ts
- api/swap/_utils.ts
- api/swap/approval/_service.ts
- api/swap/approval/index.ts
- api/swap/index.ts
This PR introduces the schema for the body of /swap* requests. It defines a structured format for describing destination actions, including the contract to call, the function signature, and a list of positional arguments to populate the call with. Each argument is represented as a structured object, allowing callers to indicate whether the value should be populated dynamically at execution time using the balance of a specified token.
The basic structure looks as follows:
```json
{
"actions": [
{
"target": "0x...", // Contract address to call
"functionSignature": "function transfer(address to, uint256 amount)", // Full function signature
"args": [ // Positional inputs for the function
{
"value": "0x...", // The argument value
"populateDynamically": false, // Whether to populate this value …
```
> feat(swap): Set body schema and validations for embedded actions

- api/_dexes/cross-swap-service.ts
- api/_dexes/utils.ts
- api/swap/_configs.ts
- api/swap/approval/_service.ts
- test/api/_dexes/cross-swap-service.test.ts
Closes ACX-4236
We can now configure a `prioritizationMode` which is used to determine the prioritized strategy. Currently it supports
- `equal-speed` - Executes all strategy fetches in parallel and returns the first one that completes.
- `priority-speed` - Executes the first `priorityChunkSize` strategy fetches in parallel and returns the first one that completes. If all of the first `priorityChunkSize` strategy fetches fail, the remaining strategy fetches are executed in parallel, and the first one that completes is returned.
> feat: add support `prioritizationMode` in strategies config

- api/swap/_utils.ts
- scripts/tests/_swap-utils.ts
This PR adds support for injecting native token balances when executing destination actions.
(All examples below are A2B transactions with tradeType = EXACT_INPUT)
The following scenarios are supported:
1. **Contract call requiring both msg.value and a dynamically populated argument:**
This case works exactly the same as ERC20 balance injection. Callers must use the zero address as the `balanceSource` to indicate that the native balance should be used. That will replace both the msg.value and the specified argument.
Example: Providing liquidity to our HubPool (requires both msg.value and balance as argument):
Deposit: [0x92d5272b021769f342366dc88b26b7fbee8ecdc5abc8a454a8d85584a32be55c](https://optimistic.etherscan.io/tx/0x92d5272b021769f342366dc88b26b7fbee8ecdc5abc8a454a8d85584a32be55c) …
> feat: support native balance injection for embedded actions

- api/_dexes/utils.ts
We were missing a drain call to send leftover tokens from the destination swap when embedded actions were included.
For example, in [this transaction](https://explorer.lens.xyz/tx/0xca1f8672a2b8fd732c5073dd27fa509b4431d64ef01cee9827939311594a0680) we received 0.996 WGHO after the swap, we unwrapped only 0.987 GHO (which matches swap.minOutputAmount). Then we execute actions with the 0.987 GHO and the difference was left in the MulticallHandler.
After the fix, this is how the transaction looks like: https://explorer.lens.xyz/tx/0x6389c1eb7360076a4af648e402bef9a15ca2e7611d6341806230ccdf53627a8e
You can see the leftover WGHO tokens are sent to the fallback recipient.
> fix: add drain call for destination swaps with embedded actions

- api/_dexes/0x/allowance-holder.ts
- api/_dexes/cross-swap-service.ts
- api/_dexes/types.ts
This PR adds support for 0x `sellEntireBalance` flag when origin + destination swaps are required.
Closes ACX-4244
MIN_OUTPUT with `3000000000000000`
- [deposit](https://optimistic.etherscan.io/tx/0x08b36ccedd40298fe4ebb9b24e89ad3350338639de1457a9f705b2dbf05e0fbd)
- [fill](https://arbiscan.io/tx/0x168c8d84835594712d3db48fd57a3b6a681ea603a1c39cbfbc0418e83f6b4425)
EXACT_INPUT with `1000000`
- [deposit](https://optimistic.etherscan.io/tx/0x026fa6a5313bb2c5ef9be87d9b1b99c0e1bddaeb68dfdf9ffc0d3b726ee1c854)
- [fill](https://arbiscan.io/tx/0x0b4d3dcaf2d39b2f1d39896e8b81683f6d26e0c91b01105953b61fd64852d128)
> feat: use `sellEntireBalance` for A2A swaps

- api/_dexes/cross-swap-service.ts
Fixes 
```
Error: LI.FI router address not found for chain id 56
at Object.getRouter (/var/task/api/_dexes/lifi/lifi-router.js:58:19)
at /var/task/api/_dexes/cross-swap-service.js:354:55
at Array.map (<anonymous>)
at _prepCrossSwapQuotesRetrievalB2A (/var/task/api/_dexes/cross-swap-service.js:352:34)
at getCrossSwapQuotesForExactInputB2A (/var/task/api/_dexes/cross-swap-service.js:148:21)
at /var/task/api/_dexes/cross-swap-service.js:61:16
at Array.map (<anonymous>)
at getCrossSwapQuoteForAmountType (/var/task/api/_dexes/cross-swap-service.js:54:39)
at getCrossSwapQuotes (/var/task/api/_dexes/cross-swap-service.js:25:16)
at handleApprovalSwap (/var/task/api/swap/approval/_service.js:28:79)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async …
```
> fix: filter out unsupported strategies when prepping b2a/a2b/a2a

- .gitignore
- package.json
- yarn.lock
closes ACX-4258
[test tx](https://app-frontend-v3-git-fix-deposit-status-tracking-uma.vercel.app/bridge/5THjSXkZEzXfs9X6Rk24zQn7CLHzk9hWFfuwynTqunR4Fiqp6DVeA9bwEUrA1BK4H3hT8G2vLanPu9ok74Khhobc?originChainId=34268394551451&destinationChainId=42161&inputTokenSymbol=USDC&outputTokenSymbol=USDC&referrer=)
> fix: solana deposit status tracking

- api/_dexes/0x/allowance-holder.ts
- api/_dexes/cross-swap-service.ts
- api/_dexes/types.ts
Avoid modifying the amount used in the destination swap when we are not using 0x.
This is making fills fail when doing USDC.e -> GHO on Lens.
Tests:
- Exact input Arbitrum USDC.e -> Lens GHO
[Deposit](https://arbiscan.io/tx/0x86169c9c55c3cb9f20beda5d330b33cb8af7ce19cbd547a20fa4309ad3e3df7f) - [Fill](https://explorer.lens.xyz/tx/0x17fa9320b1ebdcb1d6a9177029a321b6f90364315b92559c8ade10ed905f836a)  
- Exact input Optimism USDC.e -> Arbitrum AAVE
[Deposit](https://optimistic.etherscan.io/tx/0xf7b2b14411b027c4eb247930b6d307c06a8d216cefab8181fa2d7ea2aadb032a#eventlog) - [Fill](https://arbiscan.io/tx/0x49a533fbc2849b4a0fa49fe6165d824fc08f2d978cd35ebf8bfc2e75f51f6880)
- Min output Optimism USDC.e -> Arbitrum APE
[Deposit](https://optimistic.etherscan.io/tx/0x162ae8f627674c422a74d74b037c671f225c0f4 …
> fix: a2a destination swaps when not using 0x

- api/_utils.ts
- api/coingecko.ts
- api/swap/_utils.ts
- api/swap/approval/_service.ts
Attempt to make swap fees resolving more robust by:
- Adding a `fallbackResolver` param to the coingecko/price endpoint
- For tokens where we theoretically are able to resolve a price for (e.g. via LiFi) but Coingecko doesn't know of, we can now specify a fallback resolver
- Remove redundant async appFeePriceUsd fetching
> feat: more robust swap fees resolving

- api/_dexes/0x/allowance-holder.ts
- api/_dexes/types.ts
- api/_dexes/utils.ts
I found 2 issues with the current implementation of the 0x strategy's source filtering logic:
1. The 0x docs say that the parameter name must be `excludedSources`: https://0x.org/docs/api#tag/Swap/operation/swap::allowanceHolder::getQuote. We are currently setting it as `excludeSources`.
2. If the user calls our Swap API with the `includeSources` parameter set, we will convert it to an exclusion set by excluding everything except what is included. This is needed for 0x because they only accept an `excludedSources` parameter and not an `includedSources` one. But this can still cause our Swap API to not honor the inclusion list because what we store in our `sources.ts` file may not always match 0x's available sources since they may keep updating the list. So then we would invert the …
> fix: 0x source filter

- api/_auth.ts
- api/_dexes/cross-swap-service.ts
- api/_errors.ts
- api/_message.ts
- api/_utils.ts
- api/limits.ts
- api/suggested-fees.ts
- test/api/main.test.ts
This fixes a few things:
- Convert decimals for indicative quotes (this fixes USDC-BNB related swaps)
- Compact and bubble up more errors
- Allow providing message as POST body in suggested-fees and limits (sometimes Vercel would throw 414 URL_TOO_LONG errors while testing/fixing above)
> fix(swap): mismatched decimals

- api/_dexes/cross-swap-service.ts
- api/_dexes/utils.ts
- api/_multicall-handler.ts
This PR:
- Starts using MulticallHandler's `makeCallWithBalance` function to perform unwrap and transfer actions whenever the tradeType is `exactInput` or `minOutput`. This ensures we use all available balances at destination.
Some tests:
- **exactInput – B2A – usdc-eth**
- [Deposit](https://optimistic.etherscan.io/tx/0x4b8764d502ba949f0917b5742240a9f28f9669fcc65f44d0e8a69fff988c1e3e)
- [Fill](https://arbiscan.io/tx/0x72fd5832ee68ffa1003fc6f8a17bc1341760e5bc39ba58de35b3888e4d533e00)
- **minOutput – B2A – usdc-eth**
- [Deposit](https://optimistic.etherscan.io/tx/0x3897554810f7b23d4e2ef5f54b2849011c50455086d2aaee73e9024976ed7869)
- [Fill](https://arbiscan.io/tx/0x570f3d2748ab4188a5df5dbccde65f76c5756a6d2373cc150766b317a44446cf)
- Improves transactions in which we were doing two transfers …
> feat(swap): use makeCallWithBalance for exactInput and minOutput messages

- api/swap/_utils.ts
- api/swap/approval/_service.ts
- scripts/tests/_swap-utils.ts
Attempt to align percentage query param values `slippage` and `appFee`:
- `slippage` and `appFee` are expressed in range `0 <= x <= 1`, i.e. 0.01 = 1%
- `slippageTolerance` kept for backwards compatibility
> fix: align percentage query params `slippage` and `appFee`

- api/swap/_utils.ts
When setting `populateDynamically` to true, we shouldn't require the `value` field to be populated in the action since it gets overridden anyway. Currently we throw an exception in this case because we are looking for `("value" in arg)` to do the dynamic population and skip processing if it's not present.
We can fix this by only using `arg.value` if `populateDynamically` is not set and `value` is set. Else we default to 0 as it was before.
**Test case:**
Bridge + destination swap USDC to >0.005 WETH from Arbitrum to Optimism and transfer all available destination swap output token to dev wallet 2 (0x718648C8c531F91b528A7757dD2bE813c3940608). I omitted the `value` field.
```
actions: [
{
target: testCase.params.outputToken,
functionSignature: "function transfer(address to, uint256 value)", …
```
> fix: make value optional in action argument

- api/swap/_utils.ts
- scripts/tests/_swap-utils.ts
While forming the request body for embedded crosschain actions in the crosschain swap API, it was a bit confusing to grasp that `balanceSource` should actually be the token on destination chain and not the multicall Handler on the destination chain. 
Therefore to make it easier to understand for developers and integrator, we felt a better way to present this would be to call it `balanceSourceToken` to clearly indicate that a token address should be given here. Thus this PR changes `balanceSource` to `balanceSourceToken`.
> chore: change variable name for easier understanding

- api/_integrator-id.ts
- api/swap/approval/_utils.ts
This PR appends `0x73c0de` marker (0x73 = sw) to the calldata in order to identify transactions built by the Swap API.
> feat: add swap api calldata marker

- src/hooks/useAddressType.ts
- src/utils/address.ts
- src/views/Bridge/hooks/useToAccount.ts
closes ACX-4309
When selecting EVM => SVM bridge routes, `useAddressType` was incorrectly called with EVM addresses and SVM chain IDs, causing validation errors and incorrect address type detection.
- Updated `useToAccount` to only validate addresses when they match the destination chain ecosystem
- EVM addresses are only validated when destination is EVM
- SVM addresses are only validated when destination is SVM  
We currently have no use for checking if a destination address is a program or not, since we only support USDC.
BUT int he future we might want to display a warning to the user to prevent them from blackholing funds.
> check if sol address is program

- api/_dexes/lifi/utils/sources.ts
- scripts/generate-dex-sources.ts
- scripts/utils/codegen-utils.ts
We added `scripts/generate-dex-sources.ts` to `lint-staged` but this was causing frequent merge conflicts due to timestamp changes even though the actual source file did not change.
In this PR:
- Create new reusable function `writeFileWithChangeDetection` which only updates generated files if there is a change in content. This will let us leverage the same functionality for future codegen scripts.
- Update usage in `scripts/generate-dex-sources.ts`.
I tested and ensured that only a single file is updated and the other one is skipped if there are no real changes.
```
⏭️  No changes detected: /Users/ashwinswaroop/Repos/frontend/api/_dexes/0x/utils/sources.ts
✅ Updated: /Users/ashwinswaroop/Repos/frontend/api/_dexes/lifi/utils/sources.ts
```
The updated file is included in my commit for …
> fix: codegen enhancements

- src/components/Sidebar/components/WalletContent.tsx
Solana was having issues with the .once() event listener. However, the combination of ~isConnecting && isConnected is unique to our current state flow for when a wallet completes connection.
Closes ACX-4291
> fix: close sidebar on select

- api/_dexes/lifi/utils/sources.ts
- api/cron-cache-gas-prices.ts
We were trying to estimate Solana gas fees without providing a transaction, but the gas oracle needs one in order to return an estimate. See [here](https://github.com/across-protocol/sdk/blob/master/src/gasPriceOracle/adapters/solana.ts#L16).
> fix: Solana cron cache gas prices

- api/gas-prices.ts
https://app.across.to/api/gas-prices is broken due to the deposit args we are using for Solana. This PR changes the input token from WETH to USDC to simulate a deposit for calculating gas fees.
> fix: gas prices endpoint

- api/swap/_utils.ts
- test/api/swap/_utils.test.ts
Sometimes `instanceof BigNumber` doesn't work due to:
- Serialized/deserialized BigNumber that could have lost its prototype
- Conflicting ethers versions from upstream calls could cause type mistmatch
- Bundler optimization
This fixes it:
> fix: stringify all values in response JSON

- api/_dexes/utils.ts
- api/swap/_utils.ts
- api/swap/approval/_utils.ts
- src/data/examples/rpc-providers.json
While we get the approach for handling messages finalized, here are some prerequisites:
- In `buildDestinationSwapCrossChainMessage`, we should consider the destination and fallback recipients separately from the depositor
- Make recipient required for origin and destination SVM swaps
- Fix: Make input and output token in the bridge message be the bridge input and bridge output as opposed to the swap input and swap output
- Add Solana RPC to `src/data/examples/rpc-providers.json`
> fix: minor changes needed for SVM origin swaps

- api/_bridges/across/strategy.ts
- api/_bridges/index.ts
- api/_bridges/types.ts
- api/_dexes/cross-swap-service.ts
- api/swap/approval/_service.ts
The goal of this refactor is to set the stage for implementing different bridging strategies (e.g. direct bridge HyperEVM -> HyperCore, OFT, CCTP, etc.). We employ a strategy pattern (similar to the one used for DEXes). Some things I want to add as a fast follow, but left out in this PR to keep the diff small:
- Move a bunch of helpers in `api/_dexes/utils.ts` to `api/_bridges/across` that are only relevant for Across-specific message building
- Move a bunch of helpers in `api/swap/approval/_utils.ts` to `api/_bridges/across` that are only relevant for Across-specific tx building
- Add more safeguards related to bridge capabilities in `api/_dexes/cross-swap-service.ts` (makes most sense probably when we add a new bridge strategy)
> refactor: prepare multi-bridge-strategy support

- api/_balance.ts
- api/_message.ts
- api/_utils.ts
- api/limits.ts
- test/api/_message.test.ts
This adds a message validation relaxation for gas forwarding on Solana. 
[Here](https://app-frontend-v3-git-relax-recipient-contract-validat-09ba49-uma.vercel.app/api/suggested-fees?inputToken=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48&outputToken=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&destinationChainId=34268394551451&originChainId=1&recipient=GsiZqCTNRi4T3qZrixFdmhXVeA4CSUzS7c44EQ7Rw1Tw&amount=5000000&skipAmountLimit=true&allowUnmatchedDecimals=true&message=0xf649e2e88bc196def17b24eded08b15d76c77b50dc8973959f4705c4a1ee488900404b4c000000000001000000db6023a53f2cb1f57fc7a95176ad12f2080bc51f4bbb0e1aeeb722d53d779d850400000000000000) is an example request for USDC Mainnet -> Solana with an encoded gas forwarding message on Solana.
> fix: relax message for svm
